<?php 
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Processos Enviados');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        $headerColumns = array('Número', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Detalhes');
        $columns = array('numero', 'data', 'nomeManifestante', 'nomeTipoProcesso', 'nomeAssunto');
        
        $headerColumns = array('Número', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Para', 'Detalhes');
        echo $this->ajaxDataTable($this->simpleUrl('enviados', 'tramitacao-ajax'), $headerColumns)->render();
        ?>
    </form>
</div>