<?php 
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Processos Enviados');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList();

$html = '<div class="total_documents">Total de itens: <strong>' . $this->totalDocumentos . '</strong></div>';
echo $this->pagenav()->customHelperLinks($html);

echo $this->pagenav()->closeList();
?>

<div id="article">
    <?php echo $this->render('snippets/formularioPesquisaRapidaProcesso.phtml') ?>
	
    <form action="" method="post">
        <?php 
        $headerColumns = array('Número', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Detalhes');
        $columns = array('numero', 'data', 'nomeManifestante', 'nomeTipoProcesso', 'nomeAssunto');
        ?>
        
        <?php echo $this->partial('snippets/gridProcessos.phtml', array('paginator' => $this->paginator, 'exibirDestino' => true, 'exibirCheckbox' => true)) ?>
    </form>
</div>