<?php 
$this->breadcrumbs()->addPage('Protocolos', 'protocolos');
$this->breadcrumbs()->addPage('Editar Protocolo');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->link($this->simpleUrl('index'), 'Voltar');
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php
        echo $this->fieldList()->open();
        echo $this->fieldList()->textbox('Nome', 'nome', $this->protocolo->nome, array('required' => true));
        echo $this->fieldList()->select('Protocolo Pai', 'parentId', $this->listaProtocolos, $this->protocolo->parent->id, array('required' => true));
        echo $this->fieldList()->textbox('Descrição', 'descricao', $this->protocolo->descricao, array('length' => 60));
        echo $this->fieldList()->textbox('Orgão', 'orgao', $this->protocolo->orgao, array('length' => 60));
        echo $this->fieldList()->textbox('Lotação', 'lotacao', $this->protocolo->lotacao, array('length' => 60));
        echo $this->fieldList()->checkbox('Recebe pelo Subsetores', 'recebePelosSubsetores', $this->protocolo->recebePelosSubsetores);
        echo $this->fieldList()->checkbox('Recebe Malote', 'recebeMalotes', $this->protocolo->recebeMalotes);
        echo $this->fieldList()->close();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar'); 
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>