<?php echo $this->breadcrumbs()->addPage('Protocolos')->render() ?>

<?php
echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">

<?php 
$options = array('actionColumn' => array('baseUrl' => $this->simpleUrl('editar', $this->controller), 
                                         'method' => 'id', 
                                         'header' => 'Ações', 
                                         'title' => 'Editar'));
echo $this->gridProtocolos($this->lista, $options)->render();
?>
</div>
