<?php echo $this->breadcrumbs()->addPage('Protocolos')->render() ?>

<?php
echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
<?php 
echo $this->protocolo()->listaComAction($this->lista, array('baseUrl' => $this->simpleUrl('editar'), 
                                                            'title' => 'Detalhes'))->render();
?>
</div>
