<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/xhtml; charset=UTF-8" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div id="header">
            <h1><a href="#">
                Sistema de Protocolo Único</a>
                <span>Prefeitura Municipal de Fortaleza</span>
            </h1>
            
            <div id="usuario">
                Bem-vindo, <strong>Administrador</strong> | <a href="#">Cadastro</a> | <a href="#">Sair</a><br/>
                Secretaria Municipal de Saúde
            </div>
        </div>
        
       <div id="menu">
            <ul>
                <li>
                    <a href="#">Cadastros</a>
                    <ul>
                        <li><a href="#">Formulários</a></li>
                        <li><a href="../assuntos/">Assuntos</a></li>
                        <li><a href="#">Tipos de Processos</a></li>
                        <li><a href="#">Níveis</a></li>
                        <li><a href="#">Fluxogramas</a></li>
                        <li><a href="#">Envolvidos</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Processos</a>
                    <ul>
                        <li><a href="#">Tramitação</a></li>
                        <li><a href="#">Abertura</a></li>
                        <li><a href="#">Apensamento</a></li>
                        <li><a href="#">Incorporação</a></li>
                        <li><a href="#">Consulta</a></li>
                        <li><a href="#">Correção</a></li>
                        <li><a href="#">Alteração</a></li>
                        <li><a href="#">Alteração Movimento</a></li>
                        <li><a href="#">Exclusão</a></li>
                    </ul>
                </li>
            </ul>
        </div>
          
        <?php echo $this->message()->render(); ?>
          
        <?php echo $this->layout()->content ?>     
        
        <div id="footer">
            <p>
                Sistema de Protocolo Único &mdash; 
                <a href="http://www.fortaleza.ce.gov.br">Prefeitura Municipal de Fortaleza</a>
            </p>
            
            <address>Suporte: Ligue 34523476</address>
            
            <ul>
                <li><a href="#">Lista de Assuntos</a></li>
                <li><a href="#">Manual do Usuário</a></li>
            </ul>
        </div>
    </body>
</html>