<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/xhtml; charset=UTF-8" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div id="header">
            <h1><a href="#">
                Sistema de Protocolo Único</a>
                <span>Prefeitura Municipal de Fortaleza</span>
            </h1>
            
            <div id="usuario">
                Bem-vindo, <strong>Administrador</strong> | <a href="#">Cadastro</a> | <a href="#">Sair</a><br/>
                Secretaria Municipal de Saúde
            </div>
        </div>
        
        <div id="menu">
            <?php 
            $menu = $this->mainmenu();
            $menu->setAutoOrder(TRUE);
            
            $menu->addItem('Início', 'Usuário', NULL, 'index');
            $menu->addItem('Alterar Cadastro', 'Usuário', NULL, 'index');
            $menu->addItem('Sair', 'Usuário', NULL, 'logout');
            
            $menu->addItem('Assuntos', 'Cadastros', NULL, 'assuntos');
            $menu->addItem('Formulários', 'Cadastros', NULL, 'formularios');
            $menu->addItem('Lotações', 'Cadastros', NULL, 'lotacoes');
            $menu->addItem('Envolvidos', 'Cadastros', NULL, 'envolvidos');
            $menu->addItem('Tipos de Processos', 'Cadastros', NULL, 'tiposprocesso');
            $menu->addItem('Níveis', 'Cadastros', NULL, 'niveis');
            
            echo $menu->render();
            ?>
        </div>
          
        <?php echo $this->message()->render(); ?>
          
        <?php echo $this->layout()->content ?>     
        
        <div id="footer">
            <p>
                Sistema de Protocolo Único &mdash; 
                <a href="http://www.fortaleza.ce.gov.br">Prefeitura Municipal de Fortaleza</a>
            </p>
            
            <address>Suporte: Ligue 34523476</address>
            
            <ul>
                <li><a href="#">Lista de Assuntos</a></li>
                <li><a href="#">Manual do Usuário</a></li>
            </ul>
        </div>
    </body>
</html>