<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/xhtml; charset=UTF-8" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <?php flush(); ?>
    <body>
        <div id="header">
            <h1><a href="<?php echo $this->simpleUrl('index', 'index') ?>">
                Sistema de Protocolo Único</a>
                <span>Prefeitura Municipal de Fortaleza</span>
            </h1>
            
            <div id="usuario">
                Bem-vindo, <strong><?php echo $this->pessoa->nomeCompleto ?></strong> | 
                <a href="<?php echo $this->simpleUrl('cadastro', 'usuario') ?>">Cadastro</a> | 
                <a href="<?php echo $this->simpleUrl('logout', 'auth') ?>">Sair</a><br/>
                Você tem <b><?php echo $this->totalProcessosCaixaEntrada ?></b> processos na sua 
                <a href="<?php echo $this->simpleUrl('index', 'processos') ?>">Caixa de Entrada</a>.
            </div>
        </div>
        
        <div id="container">
        
        <div id="menu">
            <?php 
            $menu = $this->mainmenu();
            $menu->setAutoOrder(TRUE);
            
            $menu->addItem('Início', 'Usuário', NULL, 'index');
            $menu->addItem('Cadastro', 'Usuário', NULL, 'usuario', 'cadastro');
            $menu->addItem('Sair', 'Usuário', NULL, 'auth', 'logout');
            
            $menu->addItem('Lista Assuntos', 'Cadastros', NULL, 'assuntos');
            $menu->addItem('Envolvidos', 'Cadastros', NULL, 'envolvidos');
            $menu->addItem('Tipos de Processos', 'Cadastros', NULL, 'tiposprocesso');
            $menu->addItem('Protocolos', 'Cadastros', NULL, 'protocolos');
            
            $menu->addItem('Abertura', 'Processos', NULL, 'abrirprocesso');
            $menu->addItem('Tramitação', 'Processos', NULL, 'processos');
            $menu->addItem('Consulta', 'Processos', NULL, 'processos', 'consultar');
            $menu->addItem('Incorporação', 'Processos', NULL, 'processos', 'incorporacaoprincipal');
            $menu->addItem('Exclusão', 'Processos', NULL, 'processos', 'consultar');
            
            $menu->addItem('Envio', 'Malotes', NULL, 'relatorios');
            $menu->addItem('Recebimento', 'Malotes', NULL, 'relatorios');
            $menu->addItem('Consulta', 'Malotes', NULL, 'relatorios');
            $menu->addItem('Central', 'Malotes', NULL, 'relatorios');
            
            echo $menu->render();
            ?>
        </div>
          
        <div id="section">
          
            <?php echo $this->message()->render(); ?>
              
            <?php echo $this->layout()->content ?>
            
        </div>     
        
        </div>
        
        <div id="footer">
            <p>
                Sistema de Protocolo Único &mdash; 
                <a href="http://www.fortaleza.ce.gov.br">Prefeitura Municipal de Fortaleza</a>
            </p>
            
            <address>Suporte: Ligue 34523476</address>
            
            <ul>
                <li><a href="#">Lista de Assuntos</a></li>
                <li><a href="#">Manual do Usuário</a></li>
            </ul>
        </div>
        
    </body>
</html>