<fieldset>
    <legend>Dados Gerais do Processo Principal</legend>
    <dl>
        <dt>Número:</dt>
        <dd><b><?php echo $this->principal->numero ?></b></dd>

        <dt>Proprietário:</dt>
        <dd><b><?php echo $this->principal->proprietario->orgaoLotacao ?></b></dd>

        <dt>Status:</dt>
        <dd><b><?php echo $this->principal->status->nome ?></b></dd>

        <dt>Abertura:</dt>
        <dd><?php echo $this->principal->data ?></dd>

        <dt>Tipo:</dt>
        <dd><?php echo $this->principal->tipoProcesso->nome ?></dd>

        <dt>Assunto:</dt>
        <dd><?php echo $this->principal->assunto->nome ?></dd>

        <dt>Local Atual:</dt>
        <dd><?php echo $this->principal->protocolo->orgaoLotacao ?></dd>

        <dt>Corpo:</dt>
        <dd><?php echo $this->principal->corpo ?></dd>
    </dl>
</fieldset>

<fieldset>
    <legend>Manifestante</legend>
    <dl>
        <dt>Tipo:</dt>
        <dd><?php echo $this->principal->tipoManifestante->descricao ?></dd>

        <dt>CPF/CNPJ:</dt>
        <dd><?php echo $this->principal->manifestante->cpf ?></dd>

        <dt>Nome:</dt>
        <dd><?php echo $this->principal->manifestante->nome ?></dd>

        <?php if ($this->principal->manifestante->sexo): ?>
            <dt>Sexo:</dt>
            <dd><?php echo ($this->principal->manifestante->sexo == 'M') ? 'Masculino' : 'Feminino' ?></dd>
        <?php endif ?>

        <?php if ($this->principal->manifestante->endereco): ?>
            <dt>Endereço:</dt>
            <dd><?php echo $this->principal->manifestante->endereco ?></dd>
        <?php endif ?>

        <dt>Bairro:</dt>
        <dd><?php echo $this->principal->manifestante->nomeBairro ?></dd>

        <?php if ($this->principal->manifestante->contato): ?>
            <dt>Contato:</dt>
            <dd><?php echo $this->principal->manifestante->contato ?></dd>
        <?php endif ?>

        <?php if ($this->principal->manifestante->observacao): ?>
            <dt>Obs:</dt>
            <dd><?php echo $this->principal->manifestante->observacao ?></dd>
        <?php endif ?>
    </dl>
</fieldset>

<?php foreach ($this->apensados as $key => $apensado): ?>
    <fieldset>
        <legend>Processo Apensado <?php echo ($key+1)?></legend>
    </fieldset>
    <fieldset>
        <legend>Dados Gerais</legend>
        <dl>
            <dt>Número:</dt>
            <dd><b><?php echo $apensado->numero ?></b></dd>

            <dt>Proprietário:</dt>
            <dd><b><?php echo $apensado->proprietario->orgaoLotacao ?></b></dd>

            <dt>Status:</dt>
            <dd><b><?php echo $apensado->status->nome ?></b></dd>

            <dt>Abertura:</dt>
            <dd><?php echo $apensado->data ?></dd>

            <dt>Tipo:</dt>
            <dd><?php echo $apensado->tipoProcesso->nome ?></dd>

            <dt>Assunto:</dt>
            <dd><?php echo $apensado->assunto->nome ?></dd>

            <dt>Local Atual:</dt>
            <dd><?php echo $apensado->protocolo->orgaoLotacao ?></dd>

            <dt>Corpo:</dt>
            <dd><?php echo $apensado->corpo ?></dd>
        </dl>
    </fieldset>

    <fieldset>
        <legend>Manifestante</legend>
        <dl>
            <dt>Tipo:</dt>
            <dd><?php echo $apensado->tipoManifestante->descricao ?></dd>

            <dt>CPF/CNPJ:</dt>
            <dd><?php echo $apensado->manifestante->cpf ?></dd>

            <dt>Nome:</dt>
            <dd><?php echo $apensado->manifestante->nome ?></dd>

            <?php if ($apensado->manifestante->sexo): ?>
                <dt>Sexo:</dt>
                <dd><?php echo ($apensado->manifestante->sexo == 'M') ? 'Masculino' : 'Feminino' ?></dd>
            <?php endif ?>

            <?php if ($apensado->manifestante->endereco): ?>
                <dt>Endereço:</dt>
                <dd><?php echo $apensado->manifestante->endereco ?></dd>
            <?php endif ?>

            <dt>Bairro:</dt>
            <dd><?php echo $apensado->manifestante->nomeBairro ?></dd>

            <?php if ($apensado->manifestante->contato): ?>
                <dt>Contato:</dt>
                <dd><?php echo $apensado->manifestante->contato ?></dd>
            <?php endif ?>

            <?php if ($apensado->manifestante->observacao): ?>
                <dt>Obs:</dt>
                <dd><?php echo $apensado->manifestante->observacao ?></dd>
            <?php endif ?>
        </dl>
    </fieldset>
<?php endforeach ?>
