<fieldset>
    <legend>Dados Gerais</legend>
	<dl>
		<dt>Número:</dt>
		<dd><b><?php echo $this->processo->numero ?></b></dd>
		
		<dt>Proprietário:</dt>
		<dd><b><?php echo $this->processo->proprietario->orgaoLotacao ?></b></dd>
		
		<dt>Status:</dt>
		<dd><b><?php echo $this->processo->status->nome ?></b></dd>
		
		<dt>Abertura:</dt>
		<dd><?php echo $this->processo->data ?></dd>
		
		<dt>Tipo:</dt>
		<dd><?php echo $this->processo->tipoProcesso->nome ?></dd>
		
		<dt>Assunto:</dt>
		<dd><?php echo $this->processo->assunto->nome ?></dd>
		
		<dt>Local Atual:</dt>
		<dd><?php echo $this->processo->protocolo->orgaoLotacao ?></dd>
		
		<dt>Corpo:</dt>
		<dd><?php echo $this->processo->corpo ?></dd>
	</dl>
</fieldset>

<fieldset>
    <legend>Manifestante</legend>
    <dl>
    	<dt>Tipo:</dt>
		<dd><?php echo $this->processo->tipoManifestante->descricao ?></dd>
    
    	<dt>CPF/CNPJ:</dt>
		<dd><?php echo $this->processo->manifestante->cpf ?></dd>
		
		<dt>Nome:</dt>
		<dd><?php echo $this->processo->manifestante->nome ?></dd>
		
		<?php if ($this->processo->manifestante->sexo): ?>
		<dt>Sexo:</dt>
		<dd><?php echo ($this->processo->manifestante->sexo == 'M') ? 'Masculino' : 'Feminino' ?></dd>
		<?php endif ?>
		
		<?php if ($this->processo->manifestante->endereco): ?>
		<dt>Endereco:</dt>
		<dd><?php echo $this->processo->manifestante->endereco ?></dd>
		<?php endif ?>
		
		<dt>Bairro:</dt>
		<dd><?php echo $this->processo->manifestante->nomeBairro ?></dd>
		
		<?php if ($this->processo->manifestante->contato): ?>
		<dt>Contato:</dt>
		<dd><?php echo $this->processo->manifestante->contato ?></dd>
		<?php endif ?>
		
		<?php if ($this->processo->manifestante->observacao): ?>
		<dt>Obs:</dt>
		<dd><?php echo $this->processo->manifestante->observacao ?></dd>
		<?php endif ?>
    </dl>
</fieldset>