<fieldset>
    <legend>Dados Gerais</legend>
    <?php 
    echo $this->form()->openFieldList();
    echo $this->select('Proprietário', 'proprietarioId', $this->listaProprietarios, null, array('required' => true));
    echo $this->textbox('Data', 'data', null, array('required' => true, 'class' => 'mascaraData'));
    echo $this->textbox('Hora', 'hora', date('H:i'), array('required' => true, 'class' => 'mascaraHora'));
    echo $this->textbox('N&uacute;mero', 'numero', null, array('required' => true));
    echo $this->textbox('N&ordm; Origem', 'numeroOrigem');
    echo $this->textbox('Observa&ccedil;&atilde;o', 'observacao', null, array('length' => 60));
    echo $this->form()->closeFieldList();
    ?>
</fieldset>

<fieldset>
    <legend>Manifestante</legend>
    <?php 
    echo $this->form()->openFieldList();
    echo $this->textbox('CPF/CNPJ', 'manifestanteCpfCnpj', null, array('required' => true, 'length' => 18));
    echo $this->textbox('Nome', 'manifestanteNome', null, array('required' => true, 'length' => 60));
    echo $this->select('Bairro', 'manifestanteBairroId', $this->listaBairros, null, array('required' => true, 'length'));
    echo $this->select('Tipo', 'manifestanteTipoId', $this->listaTiposManifestante, null, array('required' => true));
    echo $this->textbox('Responsável', 'responsavel', null, array('length' => 60));
    echo $this->form()->closeFieldList();
    ?>
</fieldset>

<fieldset>
    <legend>Processo</legend>
    <?php 
    echo $this->form()->openFieldList();
    echo $this->select('Origem', 'origem', $this->listaOrigens, null, array('required' => true));
    echo $this->select('Destino', 'destino', $this->listaProtocolos, null, array('required' => true));
    echo $this->select('Prioridade', 'prioridadeId', $this->listaPrioridades, null, array('required' => true));
    echo $this->textbox('Data Prazo', 'dataPrazo', null, array('class' => 'mascaraData'));
    echo $this->textarea('Corpo', 'corpo', null, array('required' => true));
    echo $this->form()->closeFieldList();
    ?>
</fieldset>