<fieldset>
    <legend>Dados Gerais</legend>
    <?php 
    echo $this->fieldList()->open();
    echo $this->fieldList()->textbox('Data', 'data', date('d/m/Y'), array('required' => true, 'class' => 'mascaraData'));
    echo $this->fieldList()->textbox('Hora', 'hora', date('H:i'), array('required' => true, 'class' => 'mascaraHora'));
    echo $this->fieldList()->textbox('N&ordm; Origem', 'numeroOrigem');
    echo $this->fieldList()->textbox('Observa&ccedil;&atilde;o', 'observacao', null, array('length' => 60));
    echo $this->fieldList()->close();
    ?>
</fieldset>

<fieldset>
    <legend>Processo</legend>
    <?php 
    echo $this->fieldList()->open();
    
    if (!$this->tipoProcesso->tramitacao->isParalela()) {
        echo $this->protocoloSelect('Destino', 
                                    'destino', 
                                    $this->listaProtocolos, 
                                    $this->protocoloOrigemId, 
                                    $this->tipoProcesso->id, 
                                    array('required' => true));
    } else {
    	echo $this->protocoloSelectMultiple('Destinos', 
                                            'destino', 
                                            $this->listaProtocolos, 
                                            $this->protocoloOrigemId, 
                                            $this->tipoProcesso->id, 
                                            array('required' => true));
    }
    echo $this->fieldList()->select('Prioridade', 'prioridadeId', $this->listaPrioridades, null, array('required' => true));
    echo $this->fieldList()->textbox('Data Prazo', 'dataPrazo', null, array('class' => 'mascaraData'));
    
    if (!$this->tipoProcesso->tramitacao->isParalela()) {
        echo $this->ajaxSelectMultiple('Com Cópia', 
                                       'copias', 
                                       $this->simpleUrl('listar-destinos', 'protocolos-ajax'), 
                                       array('id' => 'copias'));
    }
    echo $this->fieldList()->textarea('Corpo', 'corpo', null, array('required' => true, 'length' => 5000));
    echo $this->fieldList()->close();
    ?>
</fieldset>

<?php echo $this->render('snippets/formularioProcessoFolhas.phtml') ?>
