<table class="grid">
	<thead>
		<tr>
			<th><input type="checkbox" id="checkbox_checkAll" /></th>
			<th>Número</th>
			<th>Data</th>
			<th>Envolvido</th>
			<th>Tipo</th>
			<th>Assunto</th>
			<?php if (isset($this->exibirDestino) && $this->exibirDestino == true): ?>
			<th>Destino</th>
			<?php endif ?>
			<th>Detalhes</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="2"><?php echo $this->partial('pagination.phtml', array('paginator' => $this->paginator)) ?></td>
		</tr>
	</tfoot>
	<tbody>
		<?php $i = 0 ?>
		<?php foreach ($this->paginator as $p): ?>
		<tr class="<?php echo (++$i % 2) ? 'even' : 'odd' ?>">
			<td><input type="checkbox" name="processos[]" value="<?php echo $p->id ?>" /></td>
			<td><?php echo $p->numero ?></td>
			<td><?php echo $p->data ?></td>
			<td><?php echo $p->nomeManifestante ?></td>
			<td><?php echo $p->nomeTipoProcesso ?></td>
			<td><?php echo $p->nomeAssunto ?></td>
			<?php if (isset($this->exibirDestino) && $this->exibirDestino == true): ?>
			<td><?php echo $p->nomeProtocolo ?></td>
			<?php endif ?>
			<td>
				<a href="<?php echo $this->url(array('action' => 'detalhes', 'controller' => 'processo', 'id' => $p->id)) ?>">
					Detalhes
				</a>
			</td>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>