<fieldset>
    <legend>Dados Gerais do Processo Principal</legend>
	<dl>
		<dt>Número:</dt>
		<dd><b><?php echo $this->principal->numero ?></b></dd>
		
		<dt>Proprietário:</dt>
		<dd><b><?php echo $this->principal->proprietario->orgaoLotacao ?></b></dd>
		
		<dt>Status:</dt>
		<dd><b><?php echo $this->principal->status->nome ?></b></dd>
		
		<dt>Abertura:</dt>
		<dd><?php echo $this->principal->data ?></dd>
		
		<dt>Tipo:</dt>
		<dd><?php echo $this->principal->tipoProcesso->nome ?></dd>
		
		<dt>Assunto:</dt>
		<dd><?php echo $this->principal->assunto->nome ?></dd>
		
		<dt>Local Atual:</dt>
		<dd><?php echo $this->principal->protocolo->orgaoLotacao ?></dd>
		
		<dt>Corpo:</dt>
		<dd><?php echo $this->principal->corpo ?></dd>
	</dl>
</fieldset>

<fieldset>
    <legend>Manifestante</legend>
    <dl>
    	<dt>Tipo:</dt>
		<dd><?php echo $this->principal->tipoManifestante->descricao ?></dd>
    
    	<dt>CPF/CNPJ:</dt>
		<dd><?php echo $this->principal->manifestante->cpf ?></dd>
		
		<dt>Nome:</dt>
		<dd><?php echo $this->principal->manifestante->nome ?></dd>
		
		<?php if ($this->principal->manifestante->sexo): ?>
		<dt>Sexo:</dt>
		<dd><?php echo ($this->principal->manifestante->sexo == 'M') ? 'Masculino' : 'Feminino' ?></dd>
		<?php endif ?>
		
		<?php if ($this->principal->manifestante->endereco): ?>
		<dt>Endereço:</dt>
		<dd><?php echo $this->principal->manifestante->endereco ?></dd>
		<?php endif ?>
		
		<dt>Bairro:</dt>
		<dd><?php echo $this->principal->manifestante->nomeBairro ?></dd>
		
		<?php if ($this->principal->manifestante->contato): ?>
		<dt>Contato:</dt>
		<dd><?php echo $this->principal->manifestante->contato ?></dd>
		<?php endif ?>
		
		<?php if ($this->principal->manifestante->observacao): ?>
		<dt>Obs:</dt>
		<dd><?php echo $this->principal->manifestante->observacao ?></dd>
		<?php endif ?>
    </dl>
</fieldset>

<?php foreach ($this->incorporados as $incorporado): ?>
<fieldset>
    <legend>Dados Gerais do Processo Incorporado</legend>
    <dl>
        <dt>Número:</dt>
        <dd><b><?php echo $incorporado->numero ?></b></dd>
        
        <dt>Proprietário:</dt>
        <dd><b><?php echo $incorporado->proprietario->orgaoLotacao ?></b></dd>
        
        <dt>Status:</dt>
        <dd><b><?php echo $incorporado->status->nome ?></b></dd>
        
        <dt>Abertura:</dt>
        <dd><?php echo $incorporado->data ?></dd>
        
        <dt>Tipo:</dt>
        <dd><?php echo $incorporado->tipoProcesso->nome ?></dd>
        
        <dt>Assunto:</dt>
        <dd><?php echo $incorporado->assunto->nome ?></dd>
        
        <dt>Local Atual:</dt>
        <dd><?php echo $incorporado->protocolo->orgaoLotacao ?></dd>
        
        <dt>Corpo:</dt>
        <dd><?php echo $incorporado->corpo ?></dd>
    </dl>
</fieldset>

<fieldset>
    <legend>Manifestante</legend>
    <dl>
        <dt>Tipo:</dt>
        <dd><?php echo $incorporado->tipoManifestante->descricao ?></dd>
    
        <dt>CPF/CNPJ:</dt>
        <dd><?php echo $incorporado->manifestante->cpf ?></dd>
        
        <dt>Nome:</dt>
        <dd><?php echo $incorporado->manifestante->nome ?></dd>
        
        <?php if ($incorporado->manifestante->sexo): ?>
        <dt>Sexo:</dt>
        <dd><?php echo ($incorporado->manifestante->sexo == 'M') ? 'Masculino' : 'Feminino' ?></dd>
        <?php endif ?>
        
        <?php if ($incorporado->manifestante->endereco): ?>
        <dt>Endereço:</dt>
        <dd><?php echo $incorporado->manifestante->endereco ?></dd>
        <?php endif ?>
        
        <dt>Bairro:</dt>
        <dd><?php echo $incorporado->manifestante->nomeBairro ?></dd>
        
        <?php if ($incorporado->manifestante->contato): ?>
        <dt>Contato:</dt>
        <dd><?php echo $incorporado->manifestante->contato ?></dd>
        <?php endif ?>
        
        <?php if ($incorporado->manifestante->observacao): ?>
        <dt>Obs:</dt>
        <dd><?php echo $incorporado->manifestante->observacao ?></dd>
        <?php endif ?>
    </dl>
</fieldset>
<?php endforeach ?>
