{
"sEcho": "<?php echo $this->echo ?>",
"iTotalRecords": "<?php echo $this->totalRecords ?>",
"iTotalDisplayRecords": "<?php echo $this->totalDisplayRecords ?>",
"aaData": [
<?php 
$i = 0;
foreach ($this->processos as $processo) {
	if (++$i > 1) {
		echo ',';
	}
	echo '[';
	echo '"<input type=\'checkbox\' name=\'processos[]\' value=\'"' . $processo->id . '"\' />",';
	echo '"' . $processo->numero . '",';
	echo '"' . $processo->data . '",';
	echo '"' . $processo->nomeManifestante . '",';
	echo '"' . $processo->nomeTipoProcesso . '",';
	echo '"' . $processo->nomeAssunto . '",';
	
	if (isset($this->exibirDestino) && $this->exibirDestino == true) {
		echo '"' . $processo->nomeProtocolo . '",';
	}
	
    $url = $this->simpleUrl('detalhes', 'processo', array('id' => $processo->id));
	echo '<a href="' . $url . '">Detalhes</a>';
}
?>
]
}