<?php
$this->breadcrumbs()->addPage('Apensamento', 'apensamento');
$this->breadcrumbs()->addPage('Processo Apensador');
echo $this->breadcrumbs()->render();

echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>2. Revise o Processo Principal selecionado e escolha os processos a serem apensados</h4>
    <?php
    if ($this->processo->id) {
        echo $this->render('snippets/detalhesProcesso.phtml');
    }
    ?>

    <?php
    echo $this->partial('snippets/formularioPesquisaRapidaProcessoIncorporacao.phtml', array('q' => $this->q,
        'tiposProcesso' => $this->tiposProcesso,
        'tipoProcessoId' => $this->tipoProcessoId))
    ?>
    <form action="" method="post">
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Escolher processos selecionados', 'escolherprocesso');
        echo $this->buttonlist()->close(true);
        ?>

        <div id="grid"></div>
        <?php
        if ($this->paginator) :
            echo $this->partial('snippets/gridProcessos.phtml', array('paginator' => $this->paginator, 'exibirCheckbox' => true, 'indicarPrioritarios' => true));
        else :
            $js = '
                $(function(){
                    $.ajax({
                        type: "post",
                        url: "' . $this->simpleUrl('caixa-analise', 'processos-ajax') . '",
                        success: function(retorno){
                            $("#grid").html(retorno);
                        },
                        complete: function() {
                            disableProcessoPrincipal();
                        }
                    });
                    
                });
                function disableProcessoPrincipal() {
                    $(window).scroll(function (e) {
                        var id = "'. $this->processoPrincipalId .'";
                        var linha_processo = $("input[value=" + id +"]").closest("tr");
                        if (linha_processo) {
                            linha_processo.find("input").remove().hide()
                            linha_processo.find("td:first").html("PRINCIPAL")
                            linha_processo.attr("style", "opacity:0.4;")
                            return false;
                        }
                    });
                }
                ';
            $this->headScript()->appendScript($js);
        endif;
        ?>
    </form>
</div>
