<?php 
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Caixa de Análise', 'analise');
$this->breadcrumbs()->addPage('Comprovante de Recebimento');
echo $this->breadcrumbs()->render(); 
?>

<p class="comprovante-textoabertura">Recebi os processos listados abaixo:</p>

<table class="grid">
	<thead>
		<tr>
			<th>Número</th>
			<th>Envolvido</th>
			<th>Tipo</th>
			<th>Assunto</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->processos as $p): ?>
		<tr>
			<td><?php echo $p->numero ?></td>
			<td><?php echo $p->nomeManifestante ?></td>
			<td><?php echo $p->nomeTipoProcesso ?></td>
			<td><?php echo $p->nomeAssunto ?></td>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>

<br/>
<p class="comprovante-data">Fortaleza, <?php echo date('d/m/Y - H:i') ?></p>
<p class="comprovante-assinatura"><?php echo $this->render('snippets/relatorios/assinatura.phtml');?></p>

<?php 
echo $this->pagenav()->openList(); 
echo $this->pagenav()->addLink($this->simpleUrl('index'), 'Voltar');
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>