<?php
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Caixa de Análise');
echo $this->breadcrumbs()->render();

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList();

$html = '<div class="total_documents">Total de itens: <strong>' . $this->totalDocumentos . '</strong></div>';
echo $this->pagenav()->customHelperLinks($html);

echo $this->pagenav()->closeList();
?>

<div id="article">
    <?php echo $this->render('snippets/formularioPesquisaRapidaProcesso.phtml') ?>

    <form action="" method="post">
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->defaultBlockActionsDescription();
        echo $this->buttonlist()->button('Comp. de Recepção', 'comprovanteRecebimento');
        echo $this->buttonlist()->button('Encaminhar', 'encaminhar');
        echo $this->buttonlist()->button('Criar Despacho', 'comentar');
        echo $this->buttonlist()->button('Tramit. Externa', 'externo');
        echo $this->buttonlist()->button('Arquivar', 'arquivar');
//        echo $this->buttonlist()->button('Anexar Processo Antigo', 'processo-antigo');
        echo $this->buttonlist()->close(true);
        ?>
        <div id="grid"></div>
        <?php
        if ($this->paginator) :
            echo $this->partial('snippets/gridProcessos.phtml', array('paginator' => $this->paginator, 'exibirCheckbox' => true, 'indicarPrioritarios' => true));
        else :
            $js = '
                $(function(){
                    $.ajax({
                        type: "post",
                        url: "' . $this->simpleUrl('caixa-analise', 'processos-ajax') . '",
                        success: function(retorno){
                            $("#grid").html(retorno);
                        }
                    });
                    $("td a[href*=\"/spuevolucao/processo/detalhes/id/\"]").live("click", function(e){
                        e.preventDefault();
                        window.location = $(this).attr("href") + "/origem/analise"
                    });
                });
                ';
            $this->headScript()->appendScript($js);
        endif;
        ?>
    </form>
</div>
<?php
if ($this->updateaposentadoria) :
    $js = '$(function(){
        $.ajax({
            type: "post",
            data: ' . json_encode($this->updateaposentadoria) . ',
            url: "' . $this->simpleUrl('atualizar', 'aposentadoria') . '"
        });
    });';
    $this->headScript()->appendScript($js);
endif;
?>