<?php echo $this->breadcrumbs()->addPage('Página Inicial')->render() ?>

<?php 
echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <p>
    	Bem-vindo, <b><?php echo $this->pessoa->nome ?></b>!
    </p>
    <p>
    	<?php if ($this->totalProcessosCaixaEntrada > 0): ?>
    	Você tem <b><?php echo $this->totalProcessosCaixaEntrada ?></b> processos na sua 
    	<a href="<?php echo $this->simpleUrl('entrada', 'processos') ?>">Caixa de Entrada</a>.
    	<?php else: ?>
    	Você não tem nenhum processo em sua 
    	<a href="<?php echo $this->simpleUrl('entrada', 'processos') ?>">Caixa de Entrada</a>.
    	<?php endif ?>
    </p>
</div>