<?php 
$this->breadcrumbs()->addPage('Tramitação', 'processos');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList();

$html = '<div class="total_documents">Total de itens: <strong>' . $this->totalDocumentos . '</strong></div>';
echo $this->pagenav()->customHelperLinks($html);

echo $this->pagenav()->closeList();
?>

<div id="article">
	<?php echo $this->render('snippets/formularioPesquisaRapidaProcesso.phtml') ?>

	<form action="<?php echo $this->simpleUrl('receber') ?>" method="post">
		<?php
		echo $this->buttonlist()->open();
		echo $this->buttonlist()->defaultBlockActionsDescription();
        echo $this->buttonlist()->button('Receber');
        echo $this->buttonlist()->close(true);
        ?>
        
        <?php echo $this->partial('snippets/gridProcessos.phtml', array('paginator' => $this->paginator, 'exibirCheckbox' => true, 'indicarPrioritarios' => true)) ?>
	</form>
</div>