<?php
$this->breadcrumbs()->addPage('Tramitação', 'processos');
echo $this->breadcrumbs()->render();

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList();

$html = '<div class="total_documents">Total de itens: <strong>' . $this->totalDocumentos . '</strong></div>';
echo $this->pagenav()->customHelperLinks($html);

echo $this->pagenav()->closeList();
?>

<div id="article">
    <?php echo $this->render('snippets/formularioPesquisaRapidaProcesso.phtml') ?>

    <form action="<?php echo $this->simpleUrl('receber') ?>" method="post">
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->defaultBlockActionsDescription();
        echo $this->buttonlist()->button('Receber', null, array(), array("action" => $this->simpleUrl('receber-entrada', 'processos-ajax')));
        echo $this->buttonlist()->close(true);
        ?>
        <div id="grid"></div>
        <?php
        if ($this->paginator) :
            echo $this->partial('snippets/gridProcessos.phtml', array('paginator' => $this->paginator, 'exibirCheckbox' => true, 'indicarPrioritarios' => true));
        else :
            $js = '
                $(function(){
                    $.ajax({
                        type: "post",
                        url: "' . $this->simpleUrl('caixa-entrada', 'processos-ajax') . '",
                        success: function(retorno){
                            $("#grid").html(retorno);
                        }
                    });
                });
                ';
            $this->headScript()->appendScript($js);
        endif;
        ?>
    </form>
</div>

<?php
$js = '
    $(function(){
        $("button").live("click", function(){
            var action = $(this).attr("action")
            if (action != undefined) {
                var selecionados = $("tr.marked")
                if (selecionados.length > 0 && selecionados.length < 11) {
                    selecionados.each(function(index){
                        var linha = $(this)
                        $.ajax({
                            type: "post",
                            data: {"processoId" : linha.find("td:first input").val()},
                            url: action,
                            async: false,
                            beforeSend: function(){
                                linha.find("td:first input").hide()
                                linha.find("td:first").append("<img id=\"indicator\" src=\"' . $this->baseUrl() . '/img/indicator.gif\">");
                                linha.attr("style", "opacity:0.4;")
                            },
                            success: function(retorno){
                                linha.hide();
                            }
                        });
                    });0
                    
                    window.location = "' . $this->baseUrl() . '/entrada/receber-ok"
                    return false;
                }
            }
        });
    });
    ';
$this->headScript()->appendScript($js);
?>