<?php 
$this->breadcrumbs()->addPage('Tramitação', 'processos');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="<?php echo $this->simpleUrl('receber') ?>" method="post">
        <?php
		echo $this->buttonlist()->open();
		echo $this->buttonlist()->defaultBlockActionsDescription();
        echo $this->buttonlist()->button('Receber');
        echo $this->buttonlist()->close(true); 
    	
        $headerColumns = array('', 'Número', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Detalhes');
        echo $this->ajaxDataTable($this->simpleUrl('entrada', 'tramitacao-ajax'), $headerColumns, array('searchLabel' => 'Busca por Número do Processo:'))->render();
        ?>
    </form>
</div>