<div id="section">
<?php print_r($this->messages) ?>
    <div id="login">
        <form action="<?php echo $this->simpleUrl('authorize'); ?>" method="post">
            <?php 
            echo $this->fieldList()->open();
            echo $this->fieldList()->textbox('Usuário', 'username');
            echo $this->fieldList()->password('Senha', 'password');
            echo $this->fieldList()->close();
            
            echo $this->buttonlist()->open();
            echo $this->buttonlist()->button('Entrar');
            echo $this->buttonlist()->close(); 
            
            $js = '$(document).ready(function() {
            	       $("#username").focus();
				   });';
            $this->headScript()->appendScript($js, 'text/javascript');
            ?>
        </form>
    </div>
</div>