<?php 
$this->breadcrumbs()->addPage('Assuntos', 'assuntos');
$this->breadcrumbs()->addPage((($this->isEdit) ? 'Editar' : 'Inserir') . ' Assunto');
echo $this->breadcrumbs()->render(); 
?>

<?php if ($this->isEdit): ?>
<ul class="tabs">
    <li class="active"><a href="<?php echo $this->simpleUrl('index', null, array('id' => $this->id)) ?>">Assunto</a></li>
    <li><a href="<?php echo $this->simpleUrl('formularios', null, array('assunto' => $this->id)) ?>">Formulários</a></li>
</ul>
<?php endif ?>

<?php 
echo $this->pagenav()->openList(); 
echo $this->pagenav()->link($this->simpleUrl('inserir'), 'Inserir Outro Assunto');
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        echo $this->form()->openFieldList();
        echo $this->textbox('Nome', 'nome', $this->objeto->nome, array('required' => true));
        echo $this->textarea('Corpo', 'corpo', $this->objeto->corpo, array('required' => true));
        echo $this->checkbox('Notificar na abertura', 'notificar', $this->objeto->notificar);
        echo $this->form()->closeFieldList();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>