<div id="section">
    <?php echo $this->breadcrumbs()->addPage('Assuntos')->render() ?>
    
    <?php 
    echo $this->pagenav()->openList(); 
    echo $this->pagenav()->defaultHelperLinks();
    echo $this->pagenav()->closeList();
    ?>
    
    <div id="article">
        <form action="" method="post">
            <?php 
            $headerColumns = array('Nome', 'Categoria');
            $columns = array('nome', 'categoria');
            
            $grid = new SimpleDataTable($this->lista, array('headerColumns' => $headerColumns, 'columns' => $columns));
            echo $grid->render();
            ?>
        </form>
    </div>
</div>