<?php 
$this->breadcrumbs()->addPage('Abrir Processo', 'processos');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>1. Selecione o Tipo de Processo</h4>
    <form action="" method="post">
        <?php 
        echo $this->form()->openFieldList();
        echo $this->select('Tipo de Processo', 'tipoprocesso', $this->listaTiposProcesso, $this->tipoProcesso->id, array('required' => true));
        echo $this->form()->closeFieldList();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Avançar');
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>