<?php 
header('Content-Type: application/json');
?>
{
"sEcho": "<?php echo $this->echo ?>",
"iTotalRecords": "<?php echo $this->totalRecords ?>",
"iTotalDisplayRecords": "<?php echo $this->totalDisplayRecords ?>",
"aaData": [
<?php 
$i = 0;
foreach ($this->copias as $copia) {
	if (++$i > 1) {
		echo ',';
	}
	echo '[';
	echo '"<input type=\'checkbox\' name=\'copias[]\' value=\'"' . $copia->id . '"\' />",';
	echo '"' . $copia->numeroProcesso . '",';
	echo '"' . $copia->dataProcesso . '",';
	echo '"' . $copia->nomeManifestanteProcesso . '",';
	echo '"' . $copia->nomeTipoProcesso . '",';
	echo '"' . $copia->nomeAssuntoProcesso . '",';
	
	$url = $this->simpleUrl('detalhes', 'processo', array('id' => $copia->idProcesso));
	echo '<a href="' . $url . '">Detalhes</a>';
}
?>
]
}