
<?php
$this->breadcrumbs()->addPage('Cadastro');
echo $this->breadcrumbs()->render();
?>

<?php
echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <?php
    $htmlGrupos = '';
    if ($this->pessoa->grupos) {
        foreach ($this->pessoa->grupos as $grupo) {
            $htmlGrupos .= $grupo->nome . '<br/>';
        }
    }
    
    echo $this->fieldList()->open();
	echo $this->text('Usuário', $this->pessoa->login);
	echo $this->text('Nome', $this->pessoa->nome);
	echo $this->text('Sobrenome', $this->pessoa->sobrenome);
	echo $this->text('Email', $this->pessoa->email);
	echo $this->fieldList()->close();
	?>
	
	<p>
        Caso deseje <b>alterar</b> seus dados, incluindo a sua <b>senha</b>, por favor utilize o 
        <a href="http://usuario.cti.fortaleza.ce.gov.br" target="blank" >Sistema de Cadastro &rArr;</a>.
    </p>
</div>
