<?php 
$this->breadcrumbs()->addPage('Tramitação', 'processos');
$this->breadcrumbs()->addPage('Encaminhar Processos');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<form action="" method="post">
    	<?php 
        $htmlProcessos = '<ul>';
        foreach ($this->processos as $processo) {
        	echo '<input type="hidden" name="processos[]" value="' . $processo->id . '"/>';
            $htmlProcessos .= '<li>' . $processo->nomeDescritivo . '</li>';
        }
        $htmlProcessos .= '</ul>';
        
        echo $this->fieldList()->open();
        echo $this->fieldList()->text('Processos', $htmlProcessos);
        echo $this->fieldList()->textarea('Despacho', 'despacho', null, array('required' => true));
        echo $this->fieldList()->select('Status', 'statusArquivamento', $this->listaStatusArquivamento, null, array('required' => true));
        echo $this->fieldList()->textbox('Motivo', 'motivo', null, array('length' => 60));
        echo $this->fieldList()->textbox('Local', 'local', null, array('length' => 60));
        echo $this->fieldList()->textbox('Arquivo', 'arquivo', null, array('length' => 60));
        echo $this->fieldList()->textbox('Estante', 'estante', null, array('length' => 60));
        echo $this->fieldList()->textbox('Prateleira', 'prateleira', null, array('length' => 60));
        echo $this->fieldList()->textbox('Caixa', 'caixa', null, array('length' => 60));
        echo $this->fieldList()->textbox('Pasta', 'pasta', null, array('length' => 60));
        echo $this->fieldList()->close();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>