<?php 
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Arquivo');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Reabrir Selecionados');
        echo $this->buttonlist()->close(true); 
        
        $headerColumns = array('', 'Número', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Detalhes');
        echo $this->ajaxDataTable($this->simpleUrl('arquivo', 'tramitacao-ajax'), $headerColumns)->render();
        ?>
    </form>
</div>