<?php
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Arquivo');
echo $this->breadcrumbs()->render();

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList();

$html = '<div class="total_documents">Total de itens: <strong>' . $this->totalDocumentos . '</strong></div>';
echo $this->pagenav()->customHelperLinks($html);

echo $this->pagenav()->closeList();
?>

<div id="article">
    <?php echo $this->render('snippets/formularioPesquisaRapidaProcesso.phtml') ?>

    <?php if ($this->mostrar <> 'true'){ ?>

        <a href="<?php echo $this->url(array("action" => 'index','mostrar' => 'true'))  ?>"">Listar Processos</a>

    <?php } ?>

    <?php
    if ($this->mostrar == 'true') { ?>

    <form action="" method="post">
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->defaultBlockActionsDescription();
        echo $this->buttonlist()->button('Reabrir');
        echo $this->buttonlist()->close(true);
        ?>

        <?php echo $this->partial('snippets/gridProcessos.phtml', array('paginator' => $this->paginator, 'exibirCheckbox' => true)) ?>
    </form>
<?php    } ?>
</div>

<?php
if ($this->updateaposentadoria) :
    $js = '$(function(){
        $.ajax({
            type: "post",
            data: ' . json_encode($this->updateaposentadoria) . ',
            url: "' . $this->simpleUrl('atualizar', 'aposentadoria') . '"
        });
    });';
    $this->headScript()->appendScript($js);
endif;
?>
