<div id="section">
    <?php 
    echo $this->breadcrumbs()->addPage('Desculpe, ocorreu um erro! ;/')->render();
    
    echo $this->pagenav()->openList(); 
    echo $this->pagenav()->link($this->simpleUrl('inserir'), 'Inserir Lotação');
    echo $this->pagenav()->defaultHelperLinks();
    echo $this->pagenav()->closeList();
    ?>
    <div id="article">
        <? if ('development' == APPLICATION_ENV): ?>
        <fieldset class="collapsed">
            <legend>Informação do erro:</legend>
            
            <p>
                <b>Tipo:</b> <?= $this->message ?>
            </p>
            
            <p>
              <b>Mensagem:</b> <?= $this->exception->getMessage() ?>
            </p>
            
            <h4>Ações:</h4>
            <pre><?= $this->exception->getTraceAsString() ?></pre>
            
            <h4>Parâmetros:</h4>
            <pre><? var_dump($this->request->getParams()) ?></pre>
        </fieldset>
        <? endif ?>
    </div>
</div>