<?php 
$this->breadcrumbs()->addPage('Tramitação', 'processos');
$this->breadcrumbs()->addPage('Caixa de Saída', 'processos/saida');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="<?php echo $this->simpleUrl('analise') ?>" method="post">
        <?php 
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Encaminhar', 'encaminhar');
        echo $this->buttonlist()->button('Criar Despacho', 'comentar');
        echo $this->buttonlist()->button('Tramitação Externa', 'externo');
        echo $this->buttonlist()->button('Arquivar', 'arquivar');
        echo $this->buttonlist()->close(true); 
        
        $headerColumns = array('', 'Número', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Detalhes', 'Encaminhar');
        $columns = array('numero', 'data', 'nomeManifestante', 'nomeTipoProcesso', 'nomeAssunto');
        
        $grid = new SimpleDataTable($this->lista, array('headerColumns' => $headerColumns, 'columns' => $columns));
        $grid->addCheckboxColumn('processos', 'id');
        $grid->addActionColumn('Detalhes', $this->simpleUrl('detalhes', 'processo') . '/id/', 'id');
        $grid->addActionColumn('Encaminhar', $this->simpleUrl('encaminhar', 'processo') . '/id/', 'id');
        echo $grid->render();
        ?>
    </form>
</div>