<?php 
$this->breadcrumbs()->addPage('Tramitação', 'processos');
$this->breadcrumbs()->addPage('Detalhes do Processo');
echo $this->breadcrumbs()->render(); 

echo $this->tabs()->openList();
echo $this->tabs()->addTab($this->simpleUrl('index'), 'Entrada', true);
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Análise');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Saída');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Enviados');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Cópias');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Arquivados');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Externos');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Excluídos');
echo $this->tabs()->closeList();

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<?php 
    if ($this->processo->id) {
        echo $this->render('snippets/detalhesProcesso.phtml');
    }
    ?>
</div>