<?php 
$this->breadcrumbs()->addPage('Tramitação', 'processos');
$this->breadcrumbs()->addPage('Encaminhar Processo');
echo $this->breadcrumbs()->render(); 

echo $this->tabs()->openList();
echo $this->tabs()->addTab($this->simpleUrl('index'), 'Entrada', true);
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Análise');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Saída');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Enviados');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Cópias');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Arquivados');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Externos');
echo $this->tabs()->addTab($this->simpleUrl('analise'), 'Excluídos');
echo $this->tabs()->closeList();

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<?php 
    if ($this->processo->id) {
        echo $this->render('snippets/detalhesProcesso.phtml');
    }
    ?>
    <form action="" method="post">
    	<input type="hidden" name="processoId" value="<?php echo $this->processo->id ?>"/>
        <?php
        echo $this->form()->openFieldList();
        echo $this->select('Prioridade', 'prioridadeId', $this->listaPrioridades, null, array('required' => true));
    	echo $this->select('Destino', 'destinoId', $this->listaProtocolos, null, array('required' => true));
        echo $this->textbox('Prazo', 'prazo', null, array('required' => true, 'class' => 'mascaraData'));
        echo $this->textarea('Despacho', 'despacho', null, array('required' => true));
        echo $this->form()->closeFieldList();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>