<?php 
$this->breadcrumbs()->addPage('Incorporação', 'processos/incorporacao');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="<?php echo $this->simpleUrl('analise') ?>" method="post">
        <?php 
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Incorporação', 'incorporacao');
        echo $this->buttonlist()->close(true); 
        
        $headerColumns = array('', 'Número', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Detalhes');
        $columns = array('numero', 'data', 'nomeManifestante', 'nomeTipoProcesso', 'nomeAssunto');
        
        $grid = new SimpleDataTable($this->lista, array('headerColumns' => $headerColumns, 'columns' => $columns));
        $grid->addCheckboxColumn('processos', 'id');
        $grid->addActionColumn('Detalhes', $this->simpleUrl('detalhes', 'processo') . '/id/', 'id');
        echo $grid->render();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Incorporação', 'incorporacao');
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>