<?php 
$this->breadcrumbs()->addPage('Tramitação', 'processos');
$this->breadcrumbs()->addPage('Caixa de Saída', 'processos/saida');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Cancelar Envio dos Selecionados');
        echo $this->buttonlist()->close(true); 
        
        $headerColumns = array('', 'Número', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Para', 'Detalhes');
        $columns = array('numero', 'data', 'nomeManifestante', 'nomeTipoProcesso', 'nomeAssunto', 'nomeProtocolo');
        
        $grid = new SimpleDataTable($this->lista, array('headerColumns' => $headerColumns, 'columns' => $columns));
        $grid->addCheckboxColumn('processosParaCancelarEnvio', 'id');
        $grid->addActionColumn('Detalhes', $this->simpleUrl('detalhes', 'processo') . '/id/', 'id');
        echo $grid->render();
        ?>
    </form>
</div>