<?php
$this->breadcrumbs()->addPage('Detalhes do Processo');
echo $this->breadcrumbs()->render();

echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>
<div id="article">
	<?php
    if ($this->processo->id):
        echo $this->partial('snippets/detalhesProcesso.phtml',
                            array('processo' => $this->processo,
                                  'processosParalelos' => $this->processosParalelos,
                                  'processosApensados' => $this->processosApensados,
                                  'processosIncorporados' => $this->processosIncorporados));
        echo $this->partial('snippets/movimentacoes.phtml', array('movimentacoes' => $this->processo->movimentacoes));
    ?>
    <form action="" method="get">
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Etiqueta Única', 'etiqueta');
        echo $this->buttonlist()->button('Etiqueta Dupla', 'etiqueta1');
        if ($this->oficioMarker) {
            echo $this->buttonlist()->button('Ofício', 'oficio');
        }
        if ($this->diarioMarker) {
            echo $this->buttonlist()->button('Diário', 'diario');
        }
        if ($this->comunicacaoInternaMarker) {
            echo $this->buttonlist()->button('Comunicação Interna', 'comunicacao-interna');
        }
        echo $this->buttonlist()->close();
        ?>
    </form>
    <?php endif ?>
</div>
<?php
if ($this->updateaposentadoria) :
    $js = '$(function(){
        $.ajax({
            type: "post",
            data: ' . json_encode($this->updateaposentadoria) . ',
            url: "' . $this->simpleUrl('atualizar', 'aposentadoria') . '"
        });
    });';
    $this->headScript()->appendScript($js);
endif;
if ($this->insertaposentadoria) :
    $js = '$(function(){
        $.ajax({
            type: "post",
            data: ' . json_encode($this->insertaposentadoria) . ',
            url: "'. $this->simpleUrl('enviar-dados', 'aposentadoria') . '"
        });
    });';
    $this->headScript()->appendScript($js);
endif;
?>
