<?php 
$this->breadcrumbs()->addPage('Encaminhar Processo');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<form action="" method="post">
    	<input type="hidden" name="processoId" value="<?php echo $this->processo->id ?>"/>
        <?php
        echo $this->fieldList()->open();
        echo $this->fieldList()->text('Processo', $this->processo->nomeDescritivo);
        echo $this->fieldList()->select('Prioridade', 'prioridadeId', $this->listaPrioridades, null, array('required' => true));
    	echo $this->protocoloSelect('Destino', 
                                    'destinoId', 
                                    $this->listaProtocolos, 
                                    $this->processo->protocolo->id, 
                                    null, 
                                    array('required' => true));
    	echo $this->fieldList()->textbox('Prazo', 'prazo', null, array('class' => 'mascaraData'));
        echo $this->fieldList()->textarea('Despacho', 'despacho', null, array('required' => true));
        echo $this->protocoloSelectMultiple('Com Cópia', 
                                            'copias', 
                                            $this->listaProtocolos, 
                                            $this->processo->protocolo->id);
        echo $this->fieldList()->close();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>