<?php 
$this->breadcrumbs()->addPage('Encaminhar Processo');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<?php 
    if ($this->processo->id) {
        echo $this->render('snippets/detalhesProcesso.phtml');
    }
    ?>
    <form action="" method="post">
    	<input type="hidden" name="processoId" value="<?php echo $this->processo->id ?>"/>
        <?php
        echo $this->fieldList()->open();
        echo $this->fieldList()->select('Prioridade', 'prioridadeId', $this->listaPrioridades, null, array('required' => true));
    	echo $this->fieldList()->select('Destino', 'destinoId', $this->listaProtocolos, null, array('required' => true));
        echo $this->fieldList()->textbox('Prazo', 'prazo', null, array('required' => true, 'class' => 'mascaraData'));
        echo $this->fieldList()->textarea('Despacho', 'despacho', null, array('required' => true));
        echo $this->fieldList()->close();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>