<?php 
header('Content-Type: application/json');
?>
{
"sEcho": "<?php echo $this->echo ?>",
"iTotalRecords": "<?php echo $this->totalRecords ?>",
"iTotalDisplayRecords": "<?php echo $this->totalDisplayRecords ?>",
"aaData": [
<?php 
$i = 0;
foreach ($this->protocolos as $protocolo):
	$url = $this->simpleUrl('editar', 'protocolos', array('id' => $protocolo->id));
	if (++$i > 1) echo ',';
	echo '["' . $protocolo->path . '", "<a href=\'' . $url . '\'>Detalhes</a>"]';
endforeach;
?>
]
}