<?php
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Encaminhar Processos');
echo $this->breadcrumbs()->render();

echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <div class="notice">
        Obs.: A "prioridade" e a "data prazo" continuarão os mesmos para cada processo.
    </div>
    <form action="" method="post" id="target">
        <?php
        $htmlProcessos = '</br><ul class="marked">';
        foreach ($this->processos as $processo) {
            echo '<input type="hidden" class="marked" name="processos[]" value="' . $processo->id . '"/>';
            $htmlProcessos .= '<li>' . $processo->nomeDescritivo . '</li>';
        }
        $htmlProcessos .= '</ul>';

        echo $this->fieldList()->open();
        echo $this->fieldList()->text('Processos', $htmlProcessos);
        echo $this->protocoloSelect('Destino', 'destinoId', $this->listaProtocolos, $this->origemId, null, array('required' => true));
        echo $this->fieldList()->textarea('Despacho', 'despacho', null, array('required' => true));
        echo $this->protocoloSelectMultiple('Com Cópia', 'copias', $this->listaProtocolos, $this->origemId);
        echo $this->fieldList()->close();

        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar', null, array(), array("action" => $this->simpleUrl('encaminhar-tramitar', 'processos-ajax')));
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true);
        ?>
    </form>
</div>

<?php
$js = '
    $(function(){
        $("button").live("click", function(){
            var action = $(this).attr("action")
            if (action != undefined) {
                var selecionados = $("input.marked")
                var rep_text = $(".required.valid").length == 1;
                var rep_dest = $("select#destinoId_children").length == 1
                if (rep_text && rep_dest) {
                    var processos = []
                    var items = [];
                    
                    items = $("#target").serializeArray();
                    
                    selecionados.each(function(index){
                        processos.push($(this).val())
                    });
                    
                    processos.reverse()
                    retorno = true
                    processo = processos.pop()
                    items.push({"name": "idProcesso", "value": processo})
                    
                    quantidade_processos = processos.length
                    var intervalo = setInterval(function(){
                        if (processo == undefined) {
                            clearInterval(intervalo);
                            window.location = "' . $this->baseUrl() . '/analise/encaminhar-ok"
                        } else {
                            if (processos.length != quantidade_processos) {
                                quantidade_processos = processos.length
                                retorno = true
                            }
                            if (retorno) {
                                retorno = false
                                linha = $("ul.marked li:first")
                                $.ajax({
                                    type: "post",
                                    data: items,
                                    url: action,
                                    beforeSend: function(){
                                        linha.prepend("<img id=\"indicator\" src=\"' . $this->baseUrl() . '/img/indicator.gif\">");
                                        linha.attr("style", "opacity:0.4;")
                                    },
                                    success: function(retorno){
                                        linha.remove()
                                        processo = processos.pop()
                                        items.push({"name": "idProcesso", "value": processo})
                                    },
                                    error: function(retorno) {
                                        var numero_processo = linha.text().match(/\d+/g).join("_");
                                        window.location = "' . $this->baseUrl() . '/analise/encaminhar-falha/np/" + numero_processo
                                        console.log(retorno.response)
                                        return false
                                    }
                                });
                                
                            }
                        }
                    }, 200);
                    
                    return false;
                }
            }
        });
    });
    ';
$this->headScript()->appendScript($js);
?>