<?php 
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Encaminhar Processos');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<div class="notice">
		Obs: A 'prioridade' e o 'número de folhas' continuarão os mesmos para cada processo.
	</div>
	<form action="" method="post">
    	<?php 
        $htmlProcessos = '<ul>';
        foreach ($this->processos as $processo) {
        	echo '<input type="hidden" name="processos[]" value="' . $processo->id . '"/>';
            $htmlProcessos .= '<li>' . $processo->nomeDescritivo . '</li>';
        }
        $htmlProcessos .= '</ul>';
        
        echo $this->form()->openFieldList();
        echo $this->text('Processos', $htmlProcessos);
        echo $this->select('Destino', 'destinoId', $this->listaProtocolos, null, array('required' => true, 'chooseLink' => true));
        echo $this->textarea('Despacho', 'despacho', null, array('required' => true));
        echo $this->selectPicker('Com Cópia', 'copias[]', $this->listaProtocolos, null, array('chooseLink' => true));
        echo $this->form()->closeFieldList();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>

<div id="modal-wrap" class="hidden">
	<div id="modal-overlay" class="overlay">
		<div id="modal_destinoId" class="modal">
			<?php 
		    $headerColumns = array('', 'Nome');
		    $columns = array('nome');
		        
		    $grid = new SimpleDataTable($this->protocolos, array('headerColumns' => $headerColumns, 'columns' => $columns));
		    $grid->addCheckboxColumn('processos', 'id');
		    echo $grid->render();
		    
		    echo $this->buttonlist()->open();
		    echo $this->buttonlist()->button('Escolher', null, array('onClick' => "escolherModal('modal_destinoId', 'destinoId')"));
		    echo $this->buttonlist()->resetbutton();
		    echo $this->buttonlist()->close(true);
		    ?>
		</div>
		
		<div id="modal_copias" class="modal">
			<?php 
		    $headerColumns = array('', 'Nome');
		    $columns = array('nome');
		        
		    $grid = new SimpleDataTable($this->protocolos, array('headerColumns' => $headerColumns, 'columns' => $columns));
		    $grid->addCheckboxColumn('processos', 'id');
		    echo $grid->render();
		    
		    echo $this->buttonlist()->open();
		    echo $this->buttonlist()->button('Escolher', null, array('onClick' => "escolherModal('modal_copias', 'copias')"));
		    echo $this->buttonlist()->resetbutton();
		    echo $this->buttonlist()->close(true);
		    ?>
		</div>
	</div>
</div>