<?php 
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Encaminhar Processos');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<div class="notice">
		Obs: A 'prioridade' e o 'número de folhas' continuarão os mesmos para cada processo.
	</div>
	<form action="" method="post">
    	<?php 
        $htmlProcessos = '<ul>';
        foreach ($this->processos as $processo) {
        	echo '<input type="hidden" name="processos[]" value="' . $processo->id . '"/>';
            $htmlProcessos .= '<li>' . $processo->nomeDescritivo . '</li>';
        }
        $htmlProcessos .= '</ul>';
        
        echo $this->fieldList()->open();
        echo $this->fieldList()->text('Processos', $htmlProcessos);
        echo $this->protocoloSelect('Destino', 
                                    'destinoId', 
                                    $this->listaProtocolos, 
                                    $this->origemId, 
                                    null, 
                                    array('required' => true));
        echo $this->fieldList()->textarea('Despacho', 'despacho', null, array('required' => true));
        echo $this->protocoloSelectMultiple('Com Cópia', 
                                            'copias', 
                                            $this->listaProtocolos, 
                                            $this->origemId, 
                                            null, 
                                            array('required' => true));
        echo $this->fieldList()->close();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>