<fieldset>
    <legend>Dados Gerais</legend>
    <?php 
    echo $this->form()->openFieldList();
    echo $this->select('Origem', 'origem', $this->listaOrigens, null, array('required' => true));
    echo $this->textbox('Data', 'data', null, array('required' => true, 'class' => 'mascaraData'));
    echo $this->textbox('Hora', 'hora', date('H:i'), array('required' => true, 'class' => 'mascaraHora'));
    echo $this->textbox('N&ordm; Origem', 'numeroOrigem');
    echo $this->textbox('Observa&ccedil;&atilde;o', 'observacao', null, array('length' => 60));
    echo $this->form()->closeFieldList();
    ?>
</fieldset>

<fieldset>
    <legend>Processo</legend>
    <?php 
    echo $this->form()->openFieldList();
    
    if (!$this->tipoProcesso->tramitacao->isParalela()) {
        echo $this->ajaxSelect('Destino', 
                               'destino', 
                               $this->simpleUrl('listar-destinos', 'protocolos-ajax'), 
                               $this->simpleUrl('listar-estrutura', 'protocolos-ajax'), 
                               array('Nome'), 
                               array('required' => true, 'linkName' => 'Estrutura'));
    } else {
    	echo $this->ajaxSelectMultiple('Destinos', 
    	                               'destino', 
    	                               $this->simpleUrl('listar-destinos-novo', 'protocolos-ajax'), 
    	                               array('required' => true));
    }
    echo $this->select('Prioridade', 'prioridadeId', $this->listaPrioridades, null, array('required' => true));
    echo $this->textbox('Data Prazo', 'dataPrazo', null, array('class' => 'mascaraData'));
    
    if (!$this->tipoProcesso->tramitacao->isParalela()) {
        echo $this->ajaxSelectMultiple('Com Cópia', 
                                       'copias', 
                                       $this->simpleUrl('listar-destinos-novo', 'protocolos-ajax'), 
                                       array('id' => 'copias'));
    }
    
    echo $this->textarea('Corpo', 'corpo', null, array('required' => true));
    echo $this->form()->closeFieldList();
    ?>
</fieldset>