
<fieldset>
    <legend>Manifestante</legend>
    <?php
    echo $this->fieldList()->open();
    echo $this->fieldList()->select('Tipo', 'manifestanteTipoId', $this->listaTiposManifestante, null, array('required' => true, 'id' => 'mani-tipo'));
    echo $this->fieldList()->textbox('CPF/CNPJ', 'manifestanteCpfCnpj', null, array('required' => true, 'length' => 38));
    echo $this->fieldList()->textbox('Nome', 'manifestanteNome', null, array('required' => true, 'length' => 60));
    echo '<div class="sexo">';
    echo $this->fieldList()->select(
        'Sexo',
        'manifestanteSexo',
        array('M' => 'MASCULINO', 'F' => 'FEMININO', 'N' => 'NÃO SE APLICA'),
        null,
        array('required' => true)
    );
    echo '</div>';

    echo $this->fieldList()->textbox('Responsável', 'responsavel', null, array('length' => 60));

    echo $this->fieldList()->textbox('Organização', 'manifestanteOrganizacao', null, array('length' => 60));

    echo $this->fieldList()->textbox('Logradouro', 'manifestanteLogradouro', null, array('length' => 60));
    echo $this->fieldList()->textbox('Número', 'manifestanteNumero', null, array('length' => 10));
    echo $this->fieldList()->textbox('Complemento', 'manifestanteComplemento', null, array('length' => 60));
    echo $this->fieldList()->select('Bairro', 'manifestanteBairroId', $this->listaBairros, null, array('required' => true, 'length'));
    echo $this->fieldList()->textbox('CEP', 'manifestanteCep', null, array('length' => 12, 'class' => 'mascaraCep'));
    echo $this->fieldList()->textbox('Cidade', 'manifestanteCidade', null, array('length' => 60));
    echo $this->fieldList()->select('UF', 'manifestanteUf', $this->listaUfs, null, array('required' => true));

    echo $this->fieldList()->textbox('Telefone Residencial', 'manifestanteFoneResidencial', null, array('length' => 30, 'class' => 'fone'));
    echo $this->fieldList()->textbox('Telefone Comercial', 'manifestanteFoneComercial', null, array('length' => 30, 'class' => 'fone'));
    echo $this->fieldList()->textbox('Telefone Celular', 'manifestanteFoneCelular', null, array('length' => 30, 'class' => 'fone'));

    echo $this->fieldList()->textbox('Endereço Eletrônico', 'manifestanteEmail', null, array('length' => 30));

    echo $this->fieldList()->textbox('Observação', 'manifestanteObs', null, array('length' => 60));

    echo $this->fieldList()->close();
    ?>
</fieldset>
