<fieldset>
    <legend>Dados Gerais</legend>
    <?php 
    echo $this->form()->openFieldList();
    echo $this->textbox('Data', 'data', null, array('required' => true));
    echo $this->textbox('Hora', 'hora', null, array('required' => true));
    echo $this->textbox('Número', 'numero', null, array('required' => true));
    echo $this->textbox('Obs', 'obs');
    echo $this->textbox('N&ordm; Origem', 'numeroorigem');
    echo $this->form()->closeFieldList();
    ?>
</fieldset>

<fieldset>
    <legend>Manifestante</legend>
    <?php 
    echo $this->form()->openFieldList();
    echo $this->textbox('Tipo', 'manifestantenome', null, array('required' => true));
    echo $this->textbox('CPF/CNPJ', 'manifestantecpfcnpj', null, array('required' => true));
    echo $this->textbox('Nome', 'manifestantenome', null, array('required' => true));
    echo $this->select('Bairro', 'manifestantebairro', $this->listaBairros, null, array('required' => true));
    echo $this->textbox('Responsável', 'responsavel');
    echo $this->form()->closeFieldList();
    ?>
</fieldset>

<fieldset>
    <legend>Processo</legend>
    <?php 
    echo $this->form()->openFieldList();
    echo $this->textarea('Corpo', 'corpo', null, array('required' => true));
    echo $this->select('Prioridade', 'prioridade', $this->listaPrioridades, null, array('required' => true));
    echo $this->textbox('Destino', 'destino', null, array('required' => true));
    echo $this->textbox('Data Prazo', 'dataprazo');
    echo $this->form()->closeFieldList();
    ?>
</fieldset>