<fieldset>
    <legend>Movimentações</legend>
    <ol class="historico">
    	<?php if ($this->movimentacoes): foreach ($this->movimentacoes as $movimentacao): ?>
    	<li>
    		<div class="dataMovimentacao"><?php echo $movimentacao->data ?> às <?php echo $movimentacao->hora ?></div>
    		<div class="descricaoMovimentacao"><?php echo $movimentacao->descricao ?></div>
    	</li>
    	<?php endforeach; endif ?>
    </ol>
</fieldset>