<fieldset>
    <legend>Movimentações</legend>
    <table class="grid" summary="Movimentações do processo.">
    	<thead>
    		<tr>
    			<th>Tipo</th>
    			<th>Data</th>
    			<th>De</th>
    			<th>Remetente</th>
    			<th>Para</th>
    			<th>Despacho</th>
    			<th>Prazo</th>
    		</tr>
    	</thead>
    	<tbody>
	    <?php if ($this->processo->getMovimentacoes()): foreach ($this->processo->getMovimentacoes() as $movimentacao): ?>
	    	<tr>
	    		<td><?php echo $movimentacao->tipo ?></td>
	    		<td><?php echo $movimentacao->data ?></td>
	    		<td><?php echo $movimentacao->de->descricao ?></td>
	    		<td><?php echo $movimentacao->usuario->nomeCompleto ?></td>
	    		<td><?php echo $movimentacao->para->descricao ?></td>
	    		<td><?php echo $movimentacao->despacho ?></td>
	    		<td><?php echo $movimentacao->prazo ?></td>
    		</tr>
	    <?php endforeach; endif ?>
    	</tbody>
    </table>
</fieldset>