<?php echo $this->breadcrumbs()->addPage('Página Inicial')->render() ?>

<?php 
echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <p>
    	Bem-vindo, <b><?php echo $this->pessoa->nome ?></b>!
    </p>
    <?php 
    echo $this->fieldList()->open();
    echo $this->fieldList()->text('Text', 'Value');
    echo $this->fieldList()->textbox('Textbox', 'nome', 'Value');
    echo $this->fieldList()->password('Textbox', 'senha', 'Value');
    echo $this->fieldList()->textarea('Textarea', 'descricao', 'Value');
    echo $this->fieldList()->close();
    ?>
</div>
