<?php echo $this->breadcrumbs()->addPage('Página Inicial')->render() ?>

<?php 
echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <p>
    	Bem-vindo, <b><?php echo $this->pessoa->nome ?></b>!
    </p>
    <dl>
        <?php echo $this->ajaxSelectMultiple('Destino', 'destino', $this->simpleUrl('listar-destinos', 'protocolos-ajax')) ?>
    </dl>
</div>
