<?php 
$this->breadcrumbs()->addPage('Tramitação', 'processos');
$this->breadcrumbs()->addPage('Novo Despacho');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>Escreva o despacho e, opcionalmente, anexe arquivos a ele</h4>
	<form action="" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Enviar arquivo</legend>
            <input type="hidden" name="destNodeUuid" value="<?php echo $this->processoUuid ?>" />
            <?php
            echo $this->fieldList()->open();
            echo $this->fieldList()->file('Arquivo', 'fileToUpload');
            echo $this->fieldList()->textbox('Tipo de Documento', 'tipo_documento_autocomplete');
            echo $this->fieldList()->close();
            echo $this->buttonlist()->open();
            echo $this->buttonlist()->button('Adicionar Arquivo');
            echo $this->buttonlist()->close(true); 
            ?>
            <input type='hidden' name='tipo_documento' id='tipo_documento' />
        </fieldset>
    </form>

    <fieldset>
        <legend>Lista de arquivos a ser submetida</legend>
        <ul>
            <?php
            if (empty($this->filesToUpload)) {
                echo '<li>Nenhum arquivo enviado.</li>';
            } else {
                for ($i = 0; $i < count($this->filesToUpload); $i++) {
                    //$nomeArquivo = substr(strrchr($this->filesToUpload[$i], '/'), 1);
                    $nomeArquivo = substr(strrchr($this->filesToUpload[$i]['filePath'], '/'), 1);
                    $fileDelUrl = $this->simpleUrl('removerarquivo', 'despachar', array('removerarquivo' => $i));
                    if ($this->filesToUpload[$i]['tipoDocumento']) {
                        $tipoDocumento = $this->serviceTipoDocumento->getTipoDocumento($this->filesToUpload[$i]['tipoDocumento']);
                        print "<li>$nomeArquivo -- Tipo de Documento: " . $tipoDocumento->parentRaiz . ' / '. $tipoDocumento->parent . ' / ' . $tipoDocumento->nome . " (<a href={$fileDelUrl}>Remover</a>)</li>";
                    } else {
                        print "<li>$nomeArquivo (<a href={$fileDelUrl}>Remover</a>)</li>";
                    }
                }
            }
            ?>
        </ul>
    </fieldset>
    
	<form action="" method="post">
	    <fieldset>
    	<legend>Despacho</legend>
        <?php 
        $htmlProcessos = '<ul>';
        foreach ($this->processos as $processo) {
        	echo '<input type="hidden" name="processos[]" value="' . $processo->id . '"/>';
            $htmlProcessos .= '<li>' . $processo->nomeDescritivo . '</li>';
        }
        $htmlProcessos .= '</ul>';
        
        echo $this->fieldList()->open();
        echo $this->fieldList()->text('Processos', $htmlProcessos);
        echo $this->fieldList()->textarea('Despacho', 'despacho', null, array('required' => true));
        echo $this->fieldList()->close();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar Despacho');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
        </fieldset>
    </form>
</div>

<?php
$js = "
$(document).ready(function() {
    $('#tipo_documento_autocomplete').autocomplete({
        source: '" . $this->simpleUrl('buscar', 'tipos-documentos-ajax') . "',
        select: function(event, ui) {
            $('#tipo_documento').val(ui.item.id);
        },
        change: function(event, ui) {
            //TODO checar
        }
    });

    $('#tipo_documento_autocomplete').blur(function() {
        if ($('#tipo_documento_autocomplete').val() == '') {
            $('#tipo_documento').val('');
        }
    });
});
";
$this->headScript()->appendScript($js, 'text/javascript');
?>
