<div id="section">
    <?php echo $this->breadcrumbs()->addPage('Assuntos')->render() ?>
    
    <?php 
    echo $this->pagenav()->openList(); 
    echo $this->pagenav()->addLink($this->simpleUrl('inserir'), 'Inserir Assunto');
    echo $this->pagenav()->defaultHelperLinks();
    echo $this->pagenav()->closeList();
    ?>
    
    <div id="article">
        <form action="" method="post">
            <?php 
            echo $this->buttonlist(array('class' => 'grid', 'reset' => false))->open();
            echo $this->buttonlist()->description('Ações em massa:');
            echo $this->buttonlist()->button('Excluir Selecionados', null, array('confirmation' => true));
            echo $this->buttonlist()->close(); 
            
            $columns = array('id', 'nome');
            $grid = new DataTable($this->objeto, array('method' => 'listar', 'columns' => $columns));
            echo $grid->render();
            ?>
        </form>
    </div>
</div>