<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/xhtml; charset=UTF-8" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <?php flush(); ?>
    <body>
        <div id="header">
            <h1><a href="<?php echo $this->simpleUrl('index', 'index') ?>">
                Sistema de Protocolo Único</a>
                <span>Prefeitura Municipal de Fortaleza</span>
            </h1>
            
            <div id="usuario">
                Bem-vindo, <strong><?php echo $this->pessoa->nomeCompleto ?></strong> | 
                <a href="<?php echo $this->simpleUrl('cadastro', 'usuario') ?>">Cadastro</a> | 
                <a href="<?php echo $this->simpleUrl('logout', 'auth') ?>">Sair</a><br />
                Você tem <b><?php echo $this->totalProcessosCaixaEntrada ?></b> processos na sua 
                <a href="<?php echo $this->simpleUrl('index', 'entrada') ?>">Caixa de Entrada</a>.
            </div>
        </div>
        
        <div id="container">
            <div id="menu">
            	<form action="<?php echo $this->simpleUrl('executar', 'consultar') ?>" method="post">
	            	<p id="globalSearch">
	            		<label for="search">Busca</label>
	            		<input type="text" name="globalSearch" id="search"/>
	            		<button type="submit" name="doGlobalSearch">Buscar</button>
	            	</p>
            	</form>
	            <?php 
	            $menu = $this->mainmenu();
	            $menu->setAutoOrder(TRUE);
	            
	            $menu->addItem('Início', $this->simpleUrl('index', 'index'), 'Usuário');
	            $menu->addItem('Cadastro', $this->simpleUrl('cadastro', 'usuario'), 'Usuário');
	            $menu->addItem('Sair', $this->simpleUrl('logout', 'auth'), 'Usuário');
	            
	            $menu->addItem('Lista Assuntos', $this->simpleUrl('index', 'assuntos'), 'Cadastros');
	            $menu->addItem('Envolvidos', $this->simpleUrl('index', 'envolvidos'), 'Cadastros');
	            $menu->addItem('Tipos de Processos', $this->simpleUrl('index', 'tiposprocesso'), 'Cadastros');
	            $menu->addItem('Protocolos', $this->simpleUrl('index', 'protocolos'), 'Cadastros');
	            
	            $menu->addItem('Abertura', $this->simpleUrl('index', 'abrirprocesso'), 'Processos');
	            $menu->addItem('Tramitação', $this->simpleUrl('index', 'entrada'), 'Processos');
	            $menu->addItem('Consulta', $this->simpleUrl('index', 'consultar'), 'Processos');
	            $menu->addItem('Incorporação', $this->simpleUrl('index', 'incorporacao'), 'Processos');
	            
	            $menu->addItem('Envio', $this->simpleUrl('enviar', 'malotes'), 'Malotes');
	            $menu->addItem('Recebimento', $this->simpleUrl('receber', 'malotes'), 'Malotes');
	            $menu->addItem('Consulta', $this->simpleUrl('consultar', 'malotes'), 'Malotes');
	            $menu->addItem('Central', $this->simpleUrl('index', 'malotes'), 'Malotes');
	            
	            echo $menu->render();
	            ?>
	        </div>
	          
	        <div id="section">
	            <?php echo $this->message()->render(); ?>
	            <?php echo $this->layout()->content ?>
	        </div>     
        </div>
        
        <div id="footer">
            <p>
                Sistema de Protocolo Único &mdash; 
                <a href="http://www.fortaleza.ce.gov.br">Prefeitura Municipal de Fortaleza</a>
            </p>
            
            <address>Suporte: Ligue 34523476</address>
            
            <ul>
                <li><a href="#">Lista de Assuntos</a></li>
                <li><a href="#">Manual do Usuário</a></li>
            </ul>
        </div>
    </body>
</html>