<?php 
$this->breadcrumbs()->addPage('Protocolos', 'protocolos');
$this->breadcrumbs()->addPage('Detalhes Protocolo');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->link($this->simpleUrl('index'), 'Voltar');
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php
        echo $this->fieldList()->open();
        echo $this->fieldList()->text('Nome', $this->protocolo->nome);
        echo $this->fieldList()->text('Protocolo Pai', $this->protocolo->parent->nome);
        echo  $this->fieldList()->text('Descrição', $this->protocolo->descricao);
        echo $this->fieldList()->close();
        ?>
    </form>
</div>