<?php 
$this->breadcrumbs()->addPage('Envolvidos', 'envolvidos');
$this->breadcrumbs()->addPage('Detalhes do Envolvido');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList();
echo $this->pagenav()->link($this->simpleUrl('index'), 'Voltar');
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<?php echo $this->render('snippets/detalhesManifestante.phtml') ?>
</div>