<?php 
$this->breadcrumbs()->addPage('Abrir Processo', 'abrirprocesso');
$this->breadcrumbs()->addPage('Formulário', 'abrirprocesso', 'formulario');
$this->breadcrumbs()->addPage('Formulário Envolvido', 'abrirprocesso', 'formulario');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>3. Preencha o formulário do Envolvido</h4>
    <form action="" method="post">
        <?php 
        if ($this->tipoProcesso->id) {
            echo $this->render('snippets/formularioEnvolvido.phtml');
        }
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Avançar');
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>