<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/xhtml; charset=UTF-8" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
    </head>
    <?php //flush(); ?>
    <body class="basic">
        <div id="wrapper">
            <div id="header">
                <h1>
                    <a href="#">Sistema de Protocolo Único</a>
                    <span>Prefeitura Municipal de Fortaleza</span>
                </h1>
            </div>
            
            <?php echo $this->message()->render(); ?>
              
            <?php echo $this->layout()->content ?>     
            
            <div id="footer">
                <p>
                    <a href="http://www.fortaleza.ce.gov.br">Prefeitura Municipal de Fortaleza</a>
                </p>
                
                <address>Central de Suporte: 3452-3476 / suporte.spu@cti.fortaleza.ce.gov.br</address>
            </div>
        </div>
        <?php echo $this->headScript() ?>
    </body>
</html>
