<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <?php //flush(); ?>
    <body>
    
        <div id="header">
            <h1><a href="<?php echo $this->simpleUrl('', 'index') ?>">
                Sistema de Protocolo Único</a>
                <span>Prefeitura Municipal de Fortaleza</span>
            </h1>
            
            <div id="usuario">
                Bem-vindo, <strong><?php echo $this->pessoa->nomeCompleto ?></strong> | 
                <a href="<?php echo $this->simpleUrl('cadastro', 'usuario') ?>">Cadastro</a> | 
                <a href="<?php echo $this->simpleUrl('logout', 'auth') ?>">Sair</a><br />
                Data: <strong id="current-date"><?php echo date('d/m/Y h:i') ?></strong> | Versão: <strong><?php echo $this->versao ?></strong>
            </div>
        </div>
        
        <div id="container">
            <div id="menu">
            	<form action="<?php echo $this->simpleUrl('resultados', 'consultar') ?>" method="post">
	            	<p id="globalSearch">
	            		<label for="search">Busca</label>
	            		<input type="text" name="globalSearch" id="search"/>
	            		<button type="submit" name="doGlobalSearch">Buscar</button>
	            	</p>
            	</form>
	            <?php 
	            $menu = $this->mainmenu();
	            $menu->setAutoOrder(TRUE);
	            
	            $menu->addItem('Início', $this->simpleUrl('index', 'index'), 'Usuário');
	            $menu->addItem('Cadastro', $this->simpleUrl('cadastro', 'usuario'), 'Usuário');
	            $menu->addItem('Sair', $this->simpleUrl('logout', 'auth'), 'Usuário');
	            
	            if (!$this->pessoa->isGuest()) {
		            if ($this->pessoa->isAdministrador()) {
			            $menu->addItem('Tipos de Processos', $this->simpleUrl('', 'tiposprocesso'), 'Cadastros');
			        }
		            
		            if (!$this->pessoa->isAdministrador()) {
		            	$menu->addItem('Abertura', $this->simpleUrl('', 'abrirprocesso'), 'Processos');
			            $menu->addItem('Tramitação', $this->simpleUrl('', 'entrada'), 'Processos');
			            $menu->addItem('Incorporação', $this->simpleUrl('', 'incorporacao'), 'Processos');
			            $menu->addItem('Envolvidos', $this->simpleUrl('', 'envolvidos'), 'Processos');
		            }
		            $menu->addItem('Lotações', $this->simpleUrl('', 'protocolos'), 'Processos');
		            $menu->addItem('Consulta', $this->simpleUrl('', 'consultar'), 'Processos');
		            $menu->addItem('Processos Antigos', 
		            			   'http://spu.fortaleza.ce.gov.br/spu/estrutura/index.php', 
		            			   'Processos', 
		            			   null, 
		            			   array('target' => '_blank'));
                    
		            $menu->addItem('Envio', $this->simpleUrl('enviar', 'malotes'), 'Malotes');
		            $menu->addItem('Recebimento', $this->simpleUrl('receber', 'malotes'), 'Malotes');
		            $menu->addItem('Consulta', $this->simpleUrl('consultar', 'malotes'), 'Malotes');
		            $menu->addItem('Central', $this->simpleUrl('', 'malotes'), 'Malotes');
	            }
	            
	            echo $menu->render();
	            ?>
	        </div>
	          
	        <div id="section">
	            <?php echo $this->message()->render(); ?>
	            <?php echo $this->layout()->content ?>
	        </div>     
        </div>
        
        <div id="footer">
            <p>
                Sistema de Protocolo Único &mdash; 
                <a href="http://www.fortaleza.ce.gov.br">Prefeitura Municipal de Fortaleza</a>
            </p>
            
            <address>Suporte: Ligue 34523476</address>
            
            <ul>
                <li><a href="#">Lista de Assuntos</a></li>
                <li><a href="#">Manual do Usuário</a></li>
            </ul>
        </div>
    </body>
</html>