<?php 
$this->breadcrumbs()->addPage('Envolvidos', 'envolvidos');
$this->breadcrumbs()->addPage('Editar Envolvido');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        echo $this->form()->openFieldList();
        echo $this->text('Nome', $this->manifestante->nome);
        echo $this->text('CPF', $this->manifestante->cpf);
        echo $this->text('Bairro', $this->manifestante->bairro->descricao);
        echo $this->form()->closeFieldList();
        ?>
    </form>
</div>