<?php echo $this->breadcrumbs()->addPage('Envolvidos')->render() ?>

<?php 
echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        $headerColumns = array('CPF', 'Nome', 'Ações');
        echo $this->ajaxDataTable($this->simpleUrl('listar', 'envolvidos-ajax'), $headerColumns)->render();
        ?>
    </form>
</div>