<?php
$this->breadcrumbs()->addPage('Abrir Processo', 'abrirprocesso');
$this->breadcrumbs()->addPage('Formulário', 'abrirprocesso', 'formulario');
$this->breadcrumbs()->addPage('Formulário Envolvido', 'abrirprocesso', 'formulario');
echo $this->breadcrumbs()->render();

echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>3. Preencha o formulário do Envolvido</h4>
    <form action="" method="post">
        <?php
        if ($this->tipoProcesso->id) {
            echo $this->render('snippets/formularioEnvolvido.phtml');
        }

        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Avançar');
        echo $this->buttonlist()->close(true);
        ?>
    </form>
</div>
<?php
echo $this->render('snippets/modalBuscarNome.phtml');


$js = '
    function completeAllInputs(val) {
        $.getJSON("' . $this->simpleUrl('envolvido', 'envolvidos-ajax') . '?term=" + val, function(data) {
            if (data) {
                $("#manifestanteBairroId option[value="+data.bairro+"]").attr("selected", true);
                $("#manifestanteNome").val(data.nome)
                $("#manifestanteSexo").val(data.sexo)
                $("#manifestanteLogradouro").val(data.logradouro)
                $("#manifestanteNumero").val(data.numero)
                $("#manifestanteCep").val(data.cep)
                $("#manifestanteBairro").val(data.bairro)
                $("#manifestanteCidade").val(data.cidade)
                $("#manifestanteUf").val(data.uf)
                $("#manifestanteFoneResidencial").val(data.telefone)
                $("#manifestanteFoneComercial").val(data.celular)
                $("#manifestanteFoneCelular").val(data.celular)
                $("#manifestanteObs").val(data.observacao)
                $("#manifestanteEmail").val(data.email)
                $("#manifestanteComplemento").val(data.complemento)
                $("#manifestanteOrganizacao").val(data.organizacao)
            }
        });
    }
    $(function() {
        $("#manifestanteCpfCnpj").live("blur",function() {
            if ($(this).val()) {
                completeAllInputs($(this).val());
            }
        });
    });
    ';
$this->headScript()->appendScript($js, 'text/javascript');
?>