<?php
$this->breadcrumbs()->addPage('Abrir Processo', 'abrirprocesso');
$this->breadcrumbs()->addPage('Formulário', 'abrirprocesso', 'formulario');
$this->breadcrumbs()->addPage('Formulário Envolvido', 'abrirprocesso', 'formulario');
$this->breadcrumbs()->addPage('Adição de Arquivos', 'abrirprocesso', 'uploadarquivo');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>4. Escolha arquivos para adicionar ao processo</h4>
    
    <form id="myForm" action="http://172.30.116.21:8080/alfresco/service/spu/processo/uploadarquivo?alf_ticket=TICKET_6989aee8d2c1f78a76c2c51b622b1a1bd7c96d0f" method="post" enctype="multipart/form-data">
        <dl>
	        <dt>Id do Processo</dt>
	        <dd><input type="text" name="destNodeUuid" value="<?php echo $this->processoUuid ?>" /></dd>
	    
	        <dt>Arquivo</dt>
	        <dd><input type="file" name="fileToUpload" /></dd>
	        
	        <dt></dt><dd><input type="submit" /></dd>
	    </dl>
    </form>
    
    <div id="output">
    </div>
    
    <fieldset>
    <legend>Lista de arquivos</legend>
    <?php var_dump($this->uploadedFiles); ?>
    </fieldset>
    
    <form action="" method="post">
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Avançar');
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>

<script type="text/javascript">
$(document).ready(function() {
	alert('comeco do carregamento');
    
    var options = {
            target: '#output',
            beforeSubmit: antesDoSubmit,
            success: showResponse
    };

    $('#myForm').submit(function() {
        alert('comeco do submit');
        
        // inside event callbacks 'this' is the DOM element so we first 
        // wrap it in a jQuery object and then invoke ajaxSubmit 
        $(this).ajaxSubmit(options);
 
        // !!! Important !!! 
        // always return false to prevent standard browser submit and page navigation 
        return false; 
    });
    
});

function antesDoSubmit(formData, jqForm, options) {
    var queryString = $.param(formData);
    alert('funcao antesDoSubmit. dados: ' + queryString);
    return true;
};

function showResponse(responseText, statusText, xhr) {
    alert('funcao sucesso');
    alert('status: ' + statusText + '\n\nresponseText: \n' + responseText + 
    '\n\nThe output div should have already been updated with the responseText.');
}
</script>