<?php
$this->breadcrumbs()->addPage('Abrir Processo', 'abrirprocesso');
$this->breadcrumbs()->addPage('Formulário', 'abrirprocesso', 'formulario');
$this->breadcrumbs()->addPage('Formulário Envolvido', 'abrirprocesso', 'formulario');
if ($this->hasFormulario) {
    $this->breadcrumbs()->addPage('Formulário do Assunto', 'abrirprocesso', 'formulario-assunto');	
}
$this->breadcrumbs()->addPage('Adição de Arquivos', 'abrirprocesso', 'uploadarquivo');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4><?php echo ($this->hasFormulario) ? '5' : '4' ?>. Escolha arquivos para adicionar ao processo</h4>
    
    <form action="" method="post" enctype="multipart/form-data">
        <input type="hidden" name="destNodeUuid" value="<?php echo $this->processoUuid ?>" />
        <?php
        echo $this->form()->openFieldList();
        echo $this->file('Arquivo', 'fileToUpload');
        echo $this->form()->closeFieldList();
        echo $this->buttonlist()->open();
	    echo $this->buttonlist()->button('Enviar Arquivo');
	    echo $this->buttonlist()->close(true); 
	    ?>
    </form>

    <fieldset>
    <legend>Lista de arquivos</legend>
	    <ul>
		    <?php
		    if (empty($this->uploadedFiles)) {
		    	echo '<li>Nenhum arquivo enviado.</li>';
		    } else {
		    	foreach ($this->uploadedFiles as $item) {
		    		print '<li>' . $item->nome . ' (Remover)</li>';
		    	}
		    }
		    ?>
	    </ul>
    </fieldset>
    
    <form action="" method="post">
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Avançar');
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>
