<?php
$this->breadcrumbs()->addPage('Abrir Processo', 'abrirprocesso');
$this->breadcrumbs()->addPage('Formulário', 'abrirprocesso', 'formulario');
$this->breadcrumbs()->addPage('Formulário Envolvido', 'abrirprocesso', 'formulario');
$this->breadcrumbs()->addPage('Adição de Arquivos', 'abrirprocesso', 'uploadarquivo');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>4. Escolha arquivos para adicionar ao processo</h4>
    
    <form action="" method="post" enctype="multipart/form-data">
        <input type="text" name="destNodeUuid" value="<?php echo $this->processoUuid ?>" />
        <input type="file" name="fileToUpload" />
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Enviar Arquivo');
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
    
    <fieldset>
    <legend>Lista de arquivos</legend>
    <?php var_dump($this->uploadedFiles); ?>
    </fieldset>
    
    <form action="" method="post">
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Avançar');
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>
