<?php 
header('Content-Type: application/json');
?>
{
"sEcho": "<?php echo $this->echo ?>",
"iTotalRecords": "<?php echo $this->totalRecords ?>",
"iTotalDisplayRecords": "<?php echo $this->totalDisplayRecords ?>",
"aaData": [
<?php
$i = 0;
foreach ($this->anexos as $anexo) {
	if (++$i > 1) {
		echo ',';
	}
	echo '[';
	echo '"' . $anexo->nome . '",';
	echo '"' . $anexo->processo->numero . '",';
	
	$url = $this->simpleUrl('detalhes', 'processo', array('id' => $anexo->processo->id));
	echo '"<a href=\'' . $url . '\'>Detalhes</a>"';
	echo ']';
}
?>
]
}