<?php 
$this->breadcrumbs()->addPage('Incorporação', 'incorporacao');
$this->breadcrumbs()->addPage('Processo Incorporado', 'incorporacao', 'escolherincorporado');
$this->breadcrumbs()->addPage('Processo Confirmação', 'incorporacao', 'confirmacao');
$this->breadcrumbs()->addPage('Conclusão', 'incorporacao', 'conclusao');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>4. Incorporação realizada</h4>
    <?php
    if ($this->principal->id AND $this->incorporados) {
    	// "conclusão" usa o snippet de "confirmação" porque são iguais
        echo $this->render('snippets/incorporacaoDetalhesProcessos.phtml');
    }
    ?>
</div>