<?php
$this->breadcrumbs()->addPage('Incorporação', 'incorporacao');
$this->breadcrumbs()->addPage('Processo Incorporado', 'incorporacao', 'escolherincorporado');
echo $this->breadcrumbs()->render();

echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
  <h4>2. Revise o Processo Principal selecionado e escolha o processo a ser incorporado</h4>
  <?php
  if ($this->processo->id) {
      echo $this->render('snippets/detalhesProcesso.phtml');
  }
  ?>

  <?php //echo $this->partial('snippets/formularioPesquisaRapidaProcesso.phtml', array('q' => $this->q)) ?>
  <?php
  echo $this->partial('snippets/formularioPesquisaRapidaProcessoIncorporacao.phtml',
                      array('q' => $this->q,
                            'tiposProcesso' => $this->tiposProcesso,
                            'tipoProcessoId' => $this->tipoProcessoId))
  ?>
  <form action="" method="post">
    <?php
    echo $this->buttonlist()->open();
    echo $this->buttonlist()->button('Escolher Processo Incorporado', 'incorporacao');
    echo $this->buttonlist()->close(true);
    ?>
    <?php echo $this->partial('snippets/gridProcessos.phtml',
                              array('paginator' => $this->paginator, 'exibirCheckbox' => true)) ?>
  </form>
</div>
