<?php
$this->breadcrumbs()->addPage('Incorporação', 'incorporacao');
echo $this->breadcrumbs()->render();

echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
  <h4>1. Escolha o Processo Principal (incorporador)</h4>
  <?php echo $this->partial('snippets/formularioPesquisaRapidaProcesso.phtml', array('q' => $this->q)) ?>
  <form action="" method="post">
    <?php
    echo $this->buttonlist()->open();
    echo $this->buttonlist()->button('Escolher Processo Principal', 'incorporacao');
    echo $this->buttonlist()->close(true);
    ?>

    <?php echo $this->partial('snippets/gridProcessos.phtml', array('paginator' => $this->paginator, 'exibirCheckbox' => true)) ?>
   </form>
</div>
