<?php 
echo $this->breadcrumbs()->addPage('Desculpe, ocorreu um erro! ;/')->render();
?>
<div id="article">
    <?php if ('development' == APPLICATION_ENV): ?>
    <fieldset class="collapsed">
        <legend>Informação do erro:</legend>
        
        <p>
            <b>Tipo:</b> <?php echo $this->message ?>
        </p>
        
        <p>
          <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
        </p>
        
        <h4>Descrição:</h4>
        <code><?php echo $this->exception->getDescription() ?></code>
        
        <h4>Stack Trace:</h4>
        <code><?php echo $this->exception->getTraceAsString() ?></code>
        
        <h4>Parâmetros:</h4>
        <pre><?php var_dump($this->request->getParams()) ?></pre>
    </fieldset>
    <?php endif ?>
</div>