<?php 
$this->breadcrumbs()->addPage('Tipos de Processo', 'tiposprocesso');
$this->breadcrumbs()->addPage('Editar Tipo de Processo', 'tiposprocesso', 'editar', array('id' => $this->id));
$this->breadcrumbs()->addPage('Assuntos');
echo $this->breadcrumbs()->render(); 

if ($this->isEdit):
    echo $this->tabs()->openList();
    echo $this->tabs()->addTab($this->simpleUrl('editar', null, array('id' => $this->id)), 'Dados Gerais');
    echo $this->tabs()->addTab($this->simpleUrl('assuntos', null, array('id' => $this->id)), 'Assuntos', true);
    echo $this->tabs()->closeList();
endif; 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->link($this->simpleUrl('editar', $this->controller, array('id' => $this->id)), 'Voltar');
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <?php 
    $headerColumns = array('Nome', 'Ações');
    $columns = array('nome');
    
    $grid = new SimpleDataTable($this->tipoProcesso->getAssuntos(), array('headerColumns' => $headerColumns, 'columns' => $columns));
    $grid->addActionColumn('Editar', $this->simpleUrl('editar', $this->controller) . '/id/', 'id');
    echo $grid->render();
    ?>
</div>