<?php 
$this->breadcrumbs()->addPage('Tipos de Processo', 'tiposprocesso');
$this->breadcrumbs()->addPage('Editar Tipo de Processo');
echo $this->breadcrumbs()->render(); 
?>

<?php if ($this->isEdit): ?>
<ul class="tabs">
    <li class="active"><a href="<?php echo $this->simpleUrl('editar', null, array('id' => $this->id)) ?>">Dados Gerais</a></li>
    <li><a href="<?php echo $this->simpleUrl('assuntos', null, array('id' => $this->id)) ?>">Assuntos</a></li>
</ul>
<?php endif ?>

<?php 
echo $this->pagenav()->openList(); 
echo $this->pagenav()->link($this->simpleUrl('index'), 'Voltar');
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        echo $this->form()->openFieldList();
        echo $this->textbox('Nome', 'nome', $this->tipoProcesso->nome);
        echo $this->checkbox('Simples', 'simples', $this->tipoProcesso->simples);
        echo $this->form()->closeFieldList();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>