<?php 
$this->breadcrumbs()->addPage('Tipos de Processo', 'tiposprocesso');
$this->breadcrumbs()->addPage('Editar Tipo de Processo');
echo $this->breadcrumbs()->render(); 

if ($this->isEdit) {
    echo $this->tabs()->openList();
    echo $this->tabs()->addTab($this->simpleUrl('editar', null, array('id' => $this->id)), 'Dados Gerais', true);
    echo $this->tabs()->addTab($this->simpleUrl('assuntos', null, array('id' => $this->id)), 'Assuntos');
    echo $this->tabs()->closeList();
}

echo $this->pagenav()->openList(); 
echo $this->pagenav()->link($this->simpleUrl('index'), 'Voltar');
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        echo $this->form()->openFieldList();
        echo $this->textbox('Nome', 'titulo', $this->tipoProcesso->titulo);
        echo $this->checkbox('Simples', 'simples', $this->tipoProcesso->simples);
        echo $this->form()->closeFieldList();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>