<?php 
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Cópias');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Excluir Selecionados');
        echo $this->buttonlist()->close(true); 
        
        $headerColumns = array('', 'Nome', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Detalhes');
        $columns = array('numeroProcesso', 'dataProcesso', 'nomeManifestanteProcesso', 'nomeTipoProcesso', 'nomeAssuntoProcesso');
        
        $grid = new SimpleDataTable($this->lista, array('headerColumns' => $headerColumns, 'columns' => $columns));
        $grid->addCheckboxColumn('copias', 'id');
        $grid->addActionColumn('Detalhes', $this->simpleUrl('detalhes', 'processo') . '/id/', 'idProcesso');
        echo $grid->render();
        ?>
    </form>
</div>