<?php
$this->breadcrumbs()->addPage('Apensamento', 'apensamento');
$this->breadcrumbs()->addPage('Processo Apensador', 'apensamento', 'escolherprocesso');
$this->breadcrumbs()->addPage('Processo Apensado');
echo $this->breadcrumbs()->render();

echo $this->pagenav()->openList();
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>3. Revise os processos selecionados e confirme o apensamento</h4>
    <form action="" method="post">
        <?php
        if ($this->principal->id AND $this->apensados) {
            echo $this->render('snippets/apensamentoDetalhesProcessos.phtml');
        }
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Confirmar Apensamento', 'apensamento');
        echo $this->buttonlist()->close(true);
        ?>
    </form>
</div>