{
"sEcho": "<?php echo $this->echo ?>",
"iTotalRecords": "<?php echo $this->totalRecords ?>",
"iTotalDisplayRecords": "<?php echo $this->totalDisplayRecords ?>",
"aaData": [
<?php 
$i = 0;
foreach ($this->processos as $processo) {
	if (++$i > 1) {
		echo ',';
	}
	echo '[';
	echo '"' . $processo->numero . '",';
	echo '"' . $processo->data . '",';
	echo '"' . $processo->nomeManifestante . '",';
	echo '"' . $processo->nomeTipoProcesso . '",';
	echo '"' . $processo->nomeAssunto . '",';
	echo '"' . $processo->nomeProtocolo . '",';
	
    $url = $this->simpleUrl('detalhes', 'processo', array('id' => $processo->id));
	echo '"<a href=\'' . $url . '\'>Detalhes</a>"';
	echo ']';
}
?>
]
}