<?php 
$this->breadcrumbs()->addPage('Consulta', 'consultar');
$this->breadcrumbs()->addPage('Resultados');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<?php 
	$headerColumns = array('Nome', 'Data', 'Envolvido', 'Tipo de Processo', 'Assunto', 'Ações');
	$columns = array('numero', 'data', 'nomeManifestante', 'nomeTipoProcesso', 'nomeAssunto');
        
	$grid = new SimpleDataTable($this->processos, array('headerColumns' => $headerColumns, 'columns' => $columns));
	$grid->addActionColumn('Editar', $this->simpleUrl('editar', $this->controller) . '/id/', 'id');
	echo $grid->render();
	?>
</div>