<div id="section">
    <?php 
    $this->breadcrumbs()->addPage('Lotações', 'lotacoes');
    $this->breadcrumbs()->addPage((($this->objeto->getTableKeyValue()) ? 'Editar' : 'Inserir') . ' Lotação');
    echo $this->breadcrumbs()->render(); 
    ?>
    
    <?php 
    echo $this->pagenav()->openList(); 
    echo $this->pagenav()->addLink($this->simpleUrl('inserir'), 'Inserir Outra Lotação');
    echo $this->pagenav()->defaultHelperLinks();
    echo $this->pagenav()->closeList();
    ?>
    
    <div id="article">
        <form action="" method="post">
            <?php 
            echo $this->form()->openFieldList();
            echo $this->textbox('Sigla', 'sigla', $this->objeto->sigla, array('required' => true));
            echo $this->textbox(
                'Descrição', 'descricao', $this->objeto->descricao, array('required' => true, 'length' => 120)
            );
            echo $this->textbox('Responsável', 'responsavel', $this->objeto->responsavel, array('length' => 60));
            echo $this->checkbox('Ativa', 'ativa', $this->objeto->ativa);
            echo $this->checkbox('Orgao', 'orgao', $this->objeto->orgao);
            echo $this->select(
                'Lotação Pai', 'pai', $this->objeto->getAsOptions($this->objeto->getPossiveisPais()), $this->objeto->pai
            ); 
            echo $this->form()->closeFieldList();
            echo $this->buttonlist()->open();
            echo $this->buttonlist()->button('Salvar');
            echo $this->buttonlist()->resetbutton();
            echo $this->buttonlist()->close(true); 
            ?>
        </form>
    </div>
</div>