<div id="section">
    <?php echo $this->breadcrumbs()->addPage('Lotações')->render() ?>
    
    <ul class="nav">
        <li><a href="<?php echo $this->simpleUrl('inserir') ?>">Inserir Lotação</a></li>
        <li class="imprimir"><a href="#">Imprimir</a></li>
    </ul>

    <div id="article">
        <form action="" method="post">
            <?php echo $this->buttonlist(array('class' => 'grid'))->open() ?>
                <?php echo $this->buttonlist()->description('Ações em massa:') ?>
                <?php echo $this->buttonlist()->button('Excluir Selecionados', null, array('confirmation' => true)) ?>
            <?php echo $this->buttonlist()->close() ?>
            
            <?php 
            $columns = array('id', 'sigla', 'descricao');
            $grid = new DataTable($this->objeto->getDao(), array('columns' => $columns));
            echo $grid->render() 
            ?>
        </form>
    </div>
</div>