<div id="section">
    <?php echo $this->breadcrumbs()->addPage('Lotações')->render() ?>
    
    <?php 
    echo $this->pagenav()->openList(); 
    echo $this->pagenav()->addLink($this->simpleUrl('inserir'), 'Inserir Lotação');
    echo $this->pagenav()->defaultHelperLinks();
    echo $this->pagenav()->closeList();
    ?>
    
    <div id="article">
        <form action="" method="post">
            <?php 
            echo $this->buttonlist(array('class' => 'grid', 'reset' => false))->open();
            echo $this->buttonlist()->description('Ações em massa:');
            echo $this->buttonlist()->button('Excluir Selecionados', null, array('confirmation' => true));
            echo $this->buttonlist()->close(); 
            
            $columns = array('id', 'sigla', 'descricao');
            $grid = new DataTable($this->objeto->getDao(), array('columns' => $columns));
            echo $grid->render() 
            ?>
        </form>
    </div>
</div>