<?php 
$this->breadcrumbs()->addPage('Tipos de Processo', 'tiposprocesso');
$this->breadcrumbs()->addPage('Editar Tipo de Processo', 'tiposprocesso', 'editar', array('id' => $this->id));
$this->breadcrumbs()->addPage('Assuntos');
echo $this->breadcrumbs()->render(); 

if ($this->isEdit):
    echo $this->tabs()->openList();
    echo $this->tabs()->addTab($this->simpleUrl('editar', null, array('id' => $this->id)), 'Dados Gerais');
    echo $this->tabs()->addTab($this->simpleUrl('assuntos', null, array('id' => $this->id)), 'Assuntos', true);
    echo $this->tabs()->closeList();
endif; 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->link($this->simpleUrl('editar', $this->controller, array('id' => $this->id)), 'Voltar');
echo $this->pagenav()->link($this->simpleUrl('inserir',
                                             'assuntos',
                                             array('tipoprocesso' => $this->id)),
                            'Inserir Outro Assunto');
echo $this->pagenav()->defaultHelperLinks('assuntos.html');
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="<?php echo $this->simpleUrl('remover', 'assuntos') ?>" method="post">
    <input type="hidden" name="tipoProcessoId" value="<?php echo $this->id ?>">
    <?php
    echo $this->buttonlist()->open();
    echo $this->buttonlist()->defaultBlockActionsDescription();
    echo $this->buttonlist()->button('Remover');
    echo $this->buttonlist()->close(true);
    
    $headerColumns = array('', 'Nome', 'Ações');
    $columns = array('nome');
    $grid = new SimpleDataTable($this->assuntos, array('headerColumns' => $headerColumns, 'columns' => $columns));
    $grid->addCheckboxColumn('assuntos', 'id');
    $grid->addActionColumn('Editar', $this->simpleUrl('editar', $this->action) . '/id/', 'id');
    echo $grid->render();
    ?>
    </form>
</div>