<?php 
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Caixa de Externos');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasTramitacao.phtml');

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="" method="post">
        <?php 
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->defaultBlockActionsDescription();
        echo $this->buttonlist()->button('Retornar');
        echo $this->buttonlist()->close(true); 
        
        $headerColumns = array('Número', 'Data', 'Envolvido', 'Tipo', 'Assunto', 'Detalhes');
        echo $this->ajaxDataTable($this->simpleUrl('externos', 'tramitacao-ajax'), $headerColumns, array('searchLabel' => 'Busca por Número do Processo:', 'checkboxColumn' => true))->render();
        ?>
    </form>
</div>