<?php if ($this->processoAntigo && $this->processoNovo) : ?>
    <fieldset>
        <legend>Processo Encontrado</legend>
        SS0802153504557/2012 <a id="ver" style="cursor: pointer; text-decoration: underline">ver detalhes</a>
    </fieldset>
    <div id="corpo-busca" style="display: none">
        <dl>
            <dt>Número:</dt>
            <dd><b><?php echo $this->processoAntigo->numero; ?></b></dd>

            <dt>Proprietário:</dt>
            <dd><b><?php echo $this->processoAntigo->proprietario; ?></b></dd>

            <dt>Abertura:</dt>
            <dd><?php echo $this->processoAntigo->abertura; ?></dd>

            <dt>Tipo:</dt>
            <dd><?php echo $this->processoAntigo->tipo; ?></dd>

            <dt>Assunto:</dt>
            <dd><?php echo $this->processoAntigo->assunto ?></dd>
        </dl>
    </div>
    <fieldset >
        <legend>Anexar</legend>
        <p>Deseja incorporar o processo encontrado ao processo 
            <strong><?php echo str_replace("_", "/", $this->processoNovo->nome); ?></strong>
        </p>
        <form method="POST" >
                <input type="hidden" value="<?php echo $this->processoAntigo->numero; ?>" name="idProcessoAntigo"/>
                <input type="hidden" value="<?php echo htmlentities(json_encode((array) $this->processoAntigo)); ?>" name="processoAntigo"/>
            <ul class="buttons ">
                
                <li><button type="submit" id="import" >Importar</button></li>
                <li><button type="submit" id="cancelar">Cancelar</button></li>
            </ul>
        </form>
    </fieldset>
<?php else : ?>
    <fieldset>
        <legend>Processo Não Encontrado</legend>
    </fieldset>
<?php endif; ?>