<?php 
$this->breadcrumbs()->addPage('Detalhes do Processo');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>
<div id="article">
	<?php 
    if ($this->processo->id) {
        echo $this->partial('snippets/detalhesProcesso.phtml', array('processo' => $this->processo));
        echo $this->partial('snippets/movimentacoes.phtml', array('processo' => $this->processo));
    }
    ?>
</div>