<?php 
$this->breadcrumbs()->addPage('Detalhes', 'processo', 'detalhes');
$this->breadcrumbs()->addPage($this->processo->numero);
echo $this->breadcrumbs()->render(); 
?>

<?php 
echo $this->fieldList()->open();
echo $this->fieldList()->text('Processo', $this->processo->numero);
echo $this->fieldList()->text('Abertura', $this->processo->data);
echo $this->fieldList()->text('Origem', $this->processo->proprietario->descricao);
echo $this->fieldList()->text('Assunto', $this->processo->assunto->nome);
echo $this->fieldList()->text('Envolvido', $this->processo->manifestante->nome);

if ($this->processo->observacao):
    echo $this->fieldList()->text('Observação', $this->processo->observacao);
endif;

echo $this->fieldList()->text('Descrição', $this->processo->corpo);
echo $this->fieldList()->text('Destino', $this->processo->protocolo->descricao);
echo $this->fieldList()->text('Folha', "1");

if (is_array($this->processo->arquivos)):
    $htmlAnexos = '<ul>';
    foreach ($this->processo->arquivos as $arquivo): 
        $htmlAnexos .= '<li>' . $arquivo->nome . '</li>';
    endforeach;
    $htmlAnexos .= '</ul>';
    echo $this->fieldList()->text('Anexos', $htmlAnexos);    
endif; 

echo $this->fieldList()->close();
?>

<?php 
echo $this->pagenav()->openList(); 
echo $this->pagenav()->addLink($this->simpleUrl('detalhes', 'processo', array('id' => $this->processo->id)), 'Voltar');
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>