<?php
$this->breadcrumbs()->addPage('Detalhes', 'processo', 'detalhes');
$this->breadcrumbs()->addPage($this->processo->numero);
echo $this->breadcrumbs()->render();
?>

<?php
echo $this->fieldList()->open();
echo $this->fieldList()->text('Processo', $this->processo->numero);
echo $this->fieldList()->text('Abertura', $this->processo($this)->dataAbertura());

echo $this->fieldList()->text('Origem', $this->processo($this)->proprietario());
echo $this->fieldList()->text('Assunto', $this->processo->assunto->nome);
echo $this->fieldList()->text('Envolvido', $this->processo->manifestante->nome);

if ($this->processo->observacao):
    echo $this->fieldList()->text('Observação', $this->processo->observacao);
endif;


//echo $this->fieldList()->text('Descrição', nl2br($this->processo->corpo));
echo $this->fieldList()->text('Destino', $this->processo($this)->destino());
echo $this->fieldList()->text('Folhas', $this->processo->folhas ? $this->processo->folhas->quantidade : 'sem');

if (is_array($this->processo->arquivos)):
    $htmlAnexos = '<ul>';
    foreach ($this->processo->arquivos as $arquivo):
        $htmlAnexos .= '<li>' . $arquivo->nome . '</li>';
    endforeach;
    $htmlAnexos .= '</ul>';
    if (count($this->processo->arquivos) == 0)
        $htmlAnexos = 'sem';
    echo $this->fieldList()->text('Anexos', $htmlAnexos);
endif;
echo '<span style="float:left;">Para consultar o processo, acesse:</span><br />';
echo '<h2><a href="http://www.fortaleza.ce.gov.br/consultaspu" target="_blank">www.fortaleza.ce.gov.br/consultaspu<a></h2>';
echo $this->fieldList()->close();
?>

<div id="detalhes">
    <?php
    echo $this->pagenav()->openList();
    echo $this->pagenav()->addLink($this->simpleUrl('detalhes', 'processo', array('id' => $this->processo->id)), 'Voltar');
    echo $this->pagenav()->defaultHelperLinks();
    echo $this->pagenav()->closeList();
    ?>
</div>
