<?php 
$this->breadcrumbs()->addPage('Tramitação', 'entrada');
$this->breadcrumbs()->addPage('Encaminhar Processos');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
	<div class="notice">
		Obs: A 'prioridade' e o 'número de folhas' continuarão os mesmos para cada processo.
	</div>
	<form action="" method="post">
    	<?php 
        $htmlProcessos = '<ul>';
        foreach ($this->processos as $processo) {
        	echo '<input type="hidden" name="processos[]" value="' . $processo->id . '"/>';
            $htmlProcessos .= '<li>' . $processo->nomeDescritivo . '</li>';
        }
        $htmlProcessos .= '</ul>';
        
        echo $this->fieldList()->open();
        echo $this->text('Processos', $htmlProcessos);
        echo $this->ajaxSelectMultiple('Destino', 'destinoId', $this->simpleUrl('listar-destinos', 'protocolos-ajax'), array('required' => true));
        echo $this->fieldList()->textarea('Despacho', 'despacho', null, array('required' => true));
        echo $this->ajaxSelectMultiple('Com Cópia', 'copias', $this->simpleUrl('listar-destinos', 'protocolos-ajax'), array('id' => 'copias'));
        echo $this->fieldList()->close();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Salvar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>