<?php
$this->breadcrumbs()->addPage('Consulta', 'consultar');
$this->breadcrumbs()->addPage('Resultados');
echo $this->breadcrumbs()->render();

echo $this->pagenav()->openList();

$html = '<div class="total_documents">Total de itens: <strong>' . $this->totalDocumentos . '</strong></div>';
echo $this->pagenav()->customHelperLinks($html);

echo $this->pagenav()->closeList();
?>

<div id="article">
    <table class="grid">
        <thead>
            <tr>
                <th>Local Atual</th>
                <th>Número</th>
                <th>Envolvido</th>
                <th>Tipo</th>
                <th>Assunto</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($this->processo) : ?>
            <tr>
                <td><strong><?php echo $this->processo->movimentacoes[0]->para->path; ?></strong></td>
                <td><?php echo str_replace("_", "/", $this->processo->nome); ?></td>
                <td><?php echo $this->processo->manifestante->nome; ?></td>
                <td><?php echo $this->processo->tipoProcesso->nome; ?></td>
                <td><?php echo $this->processo->assunto->nome; ?></td>
            </tr>
            <?php else: ?>
            <tr>
                <td colspan="8">Nenhum processo encontrado.</td>
            </tr>
            <?php endif ?>
        </tbody>
    </table>
</div>
