<?php 
$this->breadcrumbs()->addPage('Consulta', 'consultar');
$this->breadcrumbs()->addPage('Localizar Processo', 'consultar', 'localizar-processo');
echo $this->breadcrumbs()->render(); 

echo $this->render('snippets/abasConsulta.phtml');

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <form action="<?php echo $this->simpleUrl('localizar-processo-resultado') ?>" method="post">
        <?php 
        echo $this->fieldList()->open();
        echo $this->fieldList()->textbox('Nº Processo', 'globalSearch', null, array('required' => true, 'length' => 50));
        echo $this->fieldList()->close();
        
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Buscar');
        echo $this->buttonlist()->resetbutton();
        echo $this->buttonlist()->close(true);
        ?>
    </form>
</div>