<?php
$this->breadcrumbs()->addPage('Consulta', 'consultar');
$this->breadcrumbs()->addPage('Resultados');
echo $this->breadcrumbs()->render();

echo $this->pagenav()->openList();
if ($this->totalDocumentos) {
    $html = '<div class="total_documents">Total de itens: <strong>' . $this->totalDocumentos . '</strong></div>';
    echo $this->pagenav()->customHelperLinks($html);
} else {
    echo $this->pagenav()->openList();
}
echo $this->pagenav()->closeList();
?>

<div id="article">
    <?php echo $this->partial('snippets/gridProcessos.phtml', array('paginator' => $this->paginator)) ?>
</div>
