<?php 
$this->breadcrumbs()->addPage('Abrir Processo', 'abrirprocesso');
$this->breadcrumbs()->addPage('Formulário', 'abrirprocesso', 'formulario');
$this->breadcrumbs()->addPage('Adição de Arquivos', 'abrirprocesso', 'uploadarquivo');
$this->breadcrumbs()->addPage('Resumo e Confirmação', 'abrirprocesso', 'confirmacaocriacao');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>Revise os Dados do Processo e Confirme</h4>
    <p>Resumo</p>
    <?php
    $session = new Zend_Session_Namespace('aberturaProcesso');
    $this->processo = $session->processo;
    if ($this->processo->id) {
        echo $this->render('snippets/detalhesProcesso.phtml');
    }
    ?>
</div>