<?php 
$this->breadcrumbs()->addPage('Abrir Processo', 'abrirprocesso');
$this->breadcrumbs()->addPage('Formulário', 'abrirprocesso', 'formulario');
$this->breadcrumbs()->addPage('Adição de Arquivos', 'abrirprocesso', 'uploadarquivo');
echo $this->breadcrumbs()->render(); 

echo $this->pagenav()->openList(); 
echo $this->pagenav()->defaultHelperLinks();
echo $this->pagenav()->closeList();
?>

<div id="article">
    <h4>Escolha os Arquivos</h4>
    
    <div id="fileUpload">
        <input type="text" name="destNodeUuid" value="<?php echo $this->processoUuid ?>" />
        <h5>Fila de Envio:</h5>
        <a id="filePicker" href="#">Adicionar Arquivos</a>
        <dl id="fileList"></dl>
        <button id="uploadfiles">Enviar Arquivos Escolhidos</button>
    </div>
    
    <form action="" method="post">
        <?php
        echo $this->buttonlist()->open();
        echo $this->buttonlist()->button('Avançar');
        echo $this->buttonlist()->close(true); 
        ?>
    </form>
</div>

<script type="text/javascript">
	//Custom example logic
	jQuery(document).ready(function() {
	    var uploader = new plupload.Uploader({
	        runtimes : 'html5, html4',
	        browse_button : 'filePicker',
	        container : 'fileUpload',
	        max_file_size : '10mb',
	        url : 'http://localhost:8080/alfresco/service/spu/processo/uploadarquivo',
	        filters : [
	            {title : "Image files", extensions : "jpg,gif,png"},
	            {title : "Zip files", extensions : "zip"},
	            {title : "Log files", extensions : "log"}
	        ],
	        resize : {width : 320, height : 240, quality : 90}
	    });
	
	    $('#uploadfiles').click(function(e) {
	        uploader.start();
	        e.preventDefault();
	    });
	
	    uploader.init();
	
	    uploader.bind('FilesAdded', function(up, files) {
	        $.each(files, function(i, file) {
	            $('#fileList').append(
	    	        '<dt>' + ($('#fileList dt').size() + 1) + '</dt>' + 
	                '<dd id="' + file.id + '" class="campoTexto">' + file.name + ' (' + plupload.formatSize(file.size) + ')</dd>' 
	            );
	        });
	
	        up.refresh(); // Reposition Flash/Silverlight
	    });
	
	    uploader.bind('UploadProgress', function(up, file) {
	        $('#' + file.id + " b").html(file.percent + "%");
	    });
	
	    uploader.bind('Error', function(up, err) {
	        $('#fileList').append("<div>Error: " + err.code +
	            ", Message: " + err.message +
	            (err.file ? ", File: " + err.file.name : "") +
	            "</div>"
	        );
	
	        up.refresh(); // Reposition Flash/Silverlight
	    });
	
	    uploader.bind('FileUploaded', function(up, file) {
	        $('#' + file.id + " b").html("100%");
	    });
	});
</script>