<?php 
header('Content-Type: application/json');
?>
{
"sEcho": "<?php echo $this->echo ?>",
"iTotalRecords": "<?php echo $this->totalRecords ?>",
"iTotalDisplayRecords": "<?php echo $this->totalDisplayRecords ?>",
"aaData": [
<?php 
$i = 0;
foreach ($this->manifestantes as $manifestante) {
	if (++$i > 1) {
		echo ',';
	}
	echo '[';
	echo '"' . $manifestante->cpf . '",';
	echo '"' . $manifestante->nome . '",';
	
	$url = $this->simpleUrl('detalhes', 'envolvidos', array('cpf' => $manifestante->cpfDesformatado));
	echo '"<a href=\'' . $url . '\'>Detalhes</a>"';
	echo ']';
}
?>
]
}